# Preparation for USE

# Einwohnerdaten

In [75]:
import pandas as pd
import geopandas as gpd

PATH_RAW = "../data/prep/"

In [76]:
df_profile = pd.read_excel("../data/prep/ueberarbeitet_Stadtteilprofile Barmbek_Sued-Berichtsjahre-2013-2023.xlsx", header=[0,1])

In [77]:
df_profile.columns = [
    "_".join([str(c) for c in col if c]) 
    for col in df_profile.columns
]

In [78]:
df_profile = df_profile.dropna(how="all")
df_profile = df_profile.reset_index(drop=True)

In [79]:
df_profile.to_csv("../data/mart/df_profile_mart.csv", index=False)

In [80]:
df_profile.head()

,Berichtsjahr_Jahr,Bevölkerung und Haushalte_Anzahl der Einwohner: innen,Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren,Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung,Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren,Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung,Bevölkerung und Haushalte_Anzahl ausländischer Einwohner: innen,Bevölkerung und Haushalte_Anteil ausländischer Einwohner: innen an der Gesamt-bevölkerung,Bevölkerung und Haushalte_Anzahl der Einwohner: innen mit Migrations-hintergrund,Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung,...,Infrastruktur und Verkehr_Anzahl der Schüler:innen der Sekundarstufe I (nach Wohnort),Infrastruktur und Verkehr_Anteil der Schüler:innen in Stadtteil-schulen an allen Schüler:innen der Sekundarstufe I (nach Wohnort),Infrastruktur und Verkehr_Anteil der Schüler:innen in Gymnasien an allen Schüler:innen der Sekundarstufe I (nach Wohnort),Infrastruktur und Verkehr_Anzahl der nieder-gelassenen Ärztinnen/Ärzte,Infrastruktur und Verkehr_Anzahl der Allgemein-ärztinnen/-ärzte,Infrastruktur und Verkehr_Anzahl der Zahn-ärztinnen/-ärzte,Infrastruktur und Verkehr_Anzahl der Apotheken,Infrastruktur und Verkehr_Anzahl privater PKW,Infrastruktur und Verkehr_Anzahl der privaten PKW je 1 000 Einwohner: innen,Infrastruktur und Verkehr_Anzahl Elektro-PKW
0,2024,37091,4096,11.0,5057,13.6,6819,18.4,12704,34.3,...,1107,51.6,45.9,65,21,29,6,9746,263.0,587.0
1,2023,36705,4078,11.1,5004,13.6,6603,18.0,12315,33.6,...,1107,52.1,45.1,61,21,27,6,9885,269.0,812.0
2,2022,36452,4077,11.2,5020,13.8,6264,17.2,11809,32.4,...,1057,50.1,47.2,54,15,25,6,10073,276.0,675.0
3,2021,35709,3886,10.9,4976,13.9,5261,14.7,10609,29.7,...,978,50.6,46.5,51,14,25,6,10332,289.0,333.0
4,2020,35880,3906,10.9,5012,14.0,5096,14.2,10331,28.8,...,977,50.7,46.3,52,15,27,6,10259,286.0,251.0

In [81]:
df_profile.columns

Index(['Berichtsjahr_Jahr',
       'Bevölkerung und Haushalte_Anzahl der Einwohner: innen',
       'Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren',
       'Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren',
       'Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl ausländischer Einwohner: innen',
       'Bevölkerung und Haushalte_Anteil ausländischer Einwohner: innen an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl der Einwohner: innen mit Migrations-hintergrund',
       'Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren mit Migrations-hintergrund',
       'Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren mit Migrations-hintergrund an allen Kindern und Jugendlichen unter 18 Jahren',
       'Bevölkerung und Haushalte_Anzahl der Haushalte',
       'Bevölkerung und Haushalte_Durch-schnittliche Anzahl der Personen je Haushalt',
       'Bevölkerung und Haushalte_Anzahl der Einpersonen-haushalte',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen nur eine Person lebt, an allen Haushalten',
       'Bevölkerung und Haushalte_Anzahl der Haushalte mit Kindern',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen Kinder leben, an allen Haushalten',
       'Bevölkerung und Haushalte_Anzahl der Haushalte, in denen Allein-erziehende leben',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen Allein-erziehende leben, an allen Haushalten mit Kindern',
       'Bevölkerung und Haushalte_Fläche in km²',
       'Bevölkerung und Haushalte_Einwohner: innen je km²',
       'Bevölkerungsbewegung_Anzahl der Lebend-geborenen',
       'Bevölkerungsbewegung_Anzahl der Sterbefälle',
       'Bevölkerungsbewegung_Zuzüge über die Stadtteilgrenze pro Jahr',
       'Bevölkerungsbewegung_Fortzüge über die Stadtteilgrenze pro Jahr',
       'Bevölkerungsbewegung_Differenz der Zuzüge und Fortzüge über die Stadtteilgrenze',
       'Sozialstruktur_Sozial-versicherungs-pflichtig Beschäftigte am Wohnort',
       'Sozialstruktur_Anteil sozial-versicherungs-pflichtig Beschäftigter am Wohnort an den Erwerbs-fähigen (15 bis unter 65-Jährige)',
       'Sozialstruktur_Anzahl der Arbeitslosen',
       'Sozialstruktur_Anteil der Arbeitslosen an den Erwerbs-fähigen (15 bis unter 65-Jährige)',
       'Sozialstruktur_Jüngere Arbeitslose im Alter von 15 bis unter 25 Jahren',
       'Sozialstruktur_Anteil jüngerer Arbeitsloser (15 bis unter 25-Jährige) an den jüngeren Erwerbs-fähigen (15 bis unter 25-Jährige)',
       'Sozialstruktur_Ältere Arbeitslose im Alter von 55 bis unter 65 Jahren',
       'Sozialstruktur_Anteil älterer Arbeitsloser (55 bis unter 65-Jährige) an den älteren Erwerbs-fähigen (55 bis unter 65-Jährige)',
       'Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II',
       'Sozialstruktur_Anteil der Leistungs-empfänger: innen nach SGB II an der Gesamt-bevölkerung',
       'Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II unter 15 Jahren',
       'Sozialstruktur_Anteil der Leistungs-empfänger: innen nach SGB II unter 15 Jahren an der Bevölkerung unter 15 Jahren',
       'Sozialstruktur_Anzahl der Bedarfs-gemein-schaften nach SGB II',
       'Sozialstruktur_Empfänger:innen von Grund-sicherung im Alter der 65-Jährigen und Älteren',
       'Sozialstruktur_in % der 65-Jährigen und Älteren',
       'Sozialstruktur_Einkommen je Steuer-pflichtigen in Euro',
       'Wohnen_Anzahl der Wohngebäude', 'Wohnen_Anzahl der Wohnungen',
       'Wohnen_Anzahl der bezugsfertig gewordenen Wohnungen im Jahr',
       'Wohnen_Anzahl der Wohnungen in Ein- und Zweifamilien-häusern',
       'Wohnen_Anteil der Wohnungen in Ein- und Zweifamilien-häusern an allen Wohnungen',
       'Wohnen_Durch-schnittliche Wohnungs-größe in m²',
       'Wohnen_Durch-schnittliche Wohnfläche je Einwohner:in in m²',
       'Wohnen_Anzahl der Sozial-wohnungen',
       'Wohnen_Anteil der Sozial-wohnungen an allen Wohnungen',
       'Wohnen_Anzahl der Sozial-wohnungen mit Bindungs-auslauf bis 2029',
       'Wohnen_Anteil der Sozial-wohnungen mit Bindungs-auslauf bis 2029 an allen Sozial-wohnungen',
       'Wohnen_Durch-schnittlicher Immobilien-preis für ein Grundstück in EUR/m²',
       'Wohnen_Durch-schnittlicher Immobilien-preis für ein Ein- bzw Zweifamilien-haus in EUR/m²',
       'Wohnen_Durch-schnittlicher Immobilien-preis für eine Eigentums-wohnung in EUR/m²',
       'Infrastruktur und Verkehr_Kindergärten und Vorschul-klassen für Kinder im Alter von 3 Jahren bis Schuleintritt',
       'Infrastruktur und Verkehr_Anzahl der Grundschulen',
       'Infrastruktur und Verkehr_Anzahl der Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anteil der Schüler:innen in Stadtteil-schulen an allen Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anteil der Schüler:innen in Gymnasien an allen Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anzahl der nieder-gelassenen Ärztinnen/Ärzte',
       'Infrastruktur und Verkehr_Anzahl der Allgemein-ärztinnen/-ärzte',
       'Infrastruktur und Verkehr_Anzahl der Zahn-ärztinnen/-ärzte',
       'Infrastruktur und Verkehr_Anzahl der Apotheken',
       'Infrastruktur und Verkehr_Anzahl privater PKW',
       'Infrastruktur und Verkehr_Anzahl der privaten PKW je 1 000 Einwohner: innen',
       'Infrastruktur und Verkehr_Anzahl Elektro-PKW'],
      dtype='str')

# Untersuchung Haushalte und alles in englisch übersetzt

In [82]:
import pandas as pd

# =========================
# 1. COPY (wichtig!)
# =========================
df_households = df_profile.copy()

# =========================
# 2. RENAME
# =========================
df_households = df_households.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anteil der Haushalte, in denen nur eine Person lebt, an allen Haushalten": "single_pct",
    "Bevölkerung und Haushalte_Anteil der Haushalte, in denen Kinder leben, an allen Haushalten": "children_pct"
})

# =========================
# 3. CLEAN (Komma → Punkt)
# =========================
df_households["single_pct"] = df_households["single_pct"].astype(str).str.replace(",", ".").astype(float)
df_households["children_pct"] = df_households["children_pct"].astype(str).str.replace(",", ".").astype(float)

# =========================
# 4. OTHER
# =========================
df_households["other_pct"] = 100 - df_households["single_pct"] - df_households["children_pct"]

# =========================
# 5. DISTRICT
# =========================
df_households["district"] = "Barmbek-Süd"

# =========================
# 6. LONG FORMAT
# =========================
df_households_long = df_households.melt(
    id_vars=["year", "district"],
    value_vars=["single_pct", "children_pct", "other_pct"],
    var_name="group",
    value_name="value"
)

# =========================
# 7. LABELS
# =========================
df_households_long["group"] = df_households_long["group"].replace({
    "single_pct": "Single households",
    "children_pct": "Households with children",
    "other_pct": "Other households"
})

# =========================
# 8. EXPORT
# =========================
df_households_long.to_csv(
    "../data/mart/mart_households_structure.csv",
    index=False
)

# =========================
# 9. CHECK
# =========================
print(df_households_long.head())

   year     district              group  value
0  2024  Barmbek-Süd  Single households   68.9
1  2023  Barmbek-Süd  Single households   68.6
2  2022  Barmbek-Süd  Single households   68.2
3  2021  Barmbek-Süd  Single households   68.6
4  2020  Barmbek-Süd  Single households   68.6

# Infrastructure Barmbek Süd

In [83]:
# =========================
# INFRASTRUCTURE (COUNTS)
# =========================

df_inf = df_profile.copy()

# Rename (JETZT RICHTIG)
df_inf = df_inf.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Infrastruktur und Verkehr_Kindergärten und Vorschul-klassen für Kinder im Alter von 3 Jahren bis Schuleintritt": "kitas",
    "Infrastruktur und Verkehr_Anzahl der Grundschulen": "primary_schools",
    "Infrastruktur und Verkehr_Anzahl der nieder-gelassenen Ärztinnen/Ärzte": "doctors",
    "Infrastruktur und Verkehr_Anzahl der Allgemein-ärztinnen/-ärzte": "general_doctors",
    "Infrastruktur und Verkehr_Anzahl der Zahn-ärztinnen/-ärzte": "dentists",
    "Infrastruktur und Verkehr_Anzahl der Apotheken": "pharmacies"
})

# District
df_inf["district"] = "Barmbek-Süd"

# Auswahl
df_inf = df_inf[[
    "year", "district",
    "kitas",
    "primary_schools",
    "doctors", "general_doctors",
    "dentists", "pharmacies"
]]

# Long format
df_inf_counts = df_inf.melt(
    id_vars=["year", "district"],
    var_name="indicator",
    value_name="value"
)

# Export
df_inf_counts.to_csv(
    "../data/mart/mart_infrastructure_counts_barmbek.csv",
    index=False
)

print(df_inf_counts.head())

   year     district indicator  value
0  2024  Barmbek-Süd     kitas     27
1  2023  Barmbek-Süd     kitas     28
2  2022  Barmbek-Süd     kitas     29
3  2021  Barmbek-Süd     kitas     27
4  2020  Barmbek-Süd     kitas     27

# Education Barmbek Süd

In [84]:
# =========================
# EDUCATION (%)
# =========================

df_edu = df_profile.copy()

# Rename
df_edu = df_edu.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Infrastruktur und Verkehr_Anteil der Schüler:innen in Stadtteil-schulen an allen Schüler:innen der Sekundarstufe I (nach Wohnort)": "district_school_pct",
    "Infrastruktur und Verkehr_Anteil der Schüler:innen in Gymnasien an allen Schüler:innen der Sekundarstufe I (nach Wohnort)": "gymnasium_pct"
})

# Clean (falls nötig)
df_edu["district_school_pct"] = df_edu["district_school_pct"].astype(float)
df_edu["gymnasium_pct"] = df_edu["gymnasium_pct"].astype(float)

# District
df_edu["district"] = "Barmbek-Süd"

# Auswahl (nur %!)
df_edu = df_edu[[
    "year", "district",
    "district_school_pct", "gymnasium_pct"
]]

# Long format
df_edu_pct = df_edu.melt(
    id_vars=["year", "district"],
    var_name="indicator",
    value_name="value"
)

# Export
df_edu_pct.to_csv(
    "../data/mart/mart_education_pct_barmbek.csv",
    index=False
)

print(df_edu_pct.head())

   year     district            indicator  value
0  2024  Barmbek-Süd  district_school_pct   51.6
1  2023  Barmbek-Süd  district_school_pct   52.1
2  2022  Barmbek-Süd  district_school_pct   50.1
3  2021  Barmbek-Süd  district_school_pct   50.6
4  2020  Barmbek-Süd  district_school_pct   50.7

# Unterschiedliche Altersstrukturen

In [85]:
import pandas as pd

# =========================
# 1. COPY
# =========================
df_age = df_profile.copy()

# =========================
# 2. RENAME
# =========================
df_age = df_age.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung": "children_pct",
    "Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung": "elderly_pct"
})

# =========================
# 3. CLEAN
# =========================
df_age["children_pct"] = df_age["children_pct"].astype(str).str.replace(",", ".").astype(float)
df_age["elderly_pct"] = df_age["elderly_pct"].astype(str).str.replace(",", ".").astype(float)

# =========================
# 4. OTHER (wichtig!)
# =========================
df_age["other_pct"] = 100 - df_age["children_pct"] - df_age["elderly_pct"]

# =========================
# 5. DISTRICT
# =========================
df_age["district"] = "Barmbek-Süd"

# =========================
# 6. LONG FORMAT
# =========================
df_age_long = df_age.melt(
    id_vars=["year", "district"],
    value_vars=["children_pct", "elderly_pct", "other_pct"],
    var_name="group",
    value_name="value"
)

# =========================
# 7. LABELS
# =========================
df_age_long["group"] = df_age_long["group"].replace({
    "children_pct": "Children (<18)",
    "elderly_pct": "Elderly (65+)",
    "other_pct": "Working-age population"
})

# =========================
# 8. EXPORT
# =========================
df_age_long.to_csv(
    "../data/mart/mart_age_structure.csv",
    index=False
)

# =========================
# 9. CHECK
# =========================
print(df_age_long.head())

   year     district           group  value
0  2024  Barmbek-Süd  Children (<18)   11.0
1  2023  Barmbek-Süd  Children (<18)   11.1
2  2022  Barmbek-Süd  Children (<18)   11.2
3  2021  Barmbek-Süd  Children (<18)   10.9
4  2020  Barmbek-Süd  Children (<18)   10.9

# Autobesitzer

In [86]:
import pandas as pd

# =========================
# 1. COPY
# =========================
df_cars = df_profile.copy()

# =========================
# 2. RENAME
# =========================
df_cars = df_cars.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Infrastruktur und Verkehr_Anzahl der privaten PKW je 1 000 Einwohner: innen": "cars_per_1000"
})

# =========================
# 3. CLEAN
# =========================
df_cars["cars_per_1000"] = df_cars["cars_per_1000"].astype(str).str.replace(",", ".").astype(float)

# =========================
# 4. INTO %
# =========================
df_cars["car_owner_pct"] = df_cars["cars_per_1000"] / 10
df_cars["no_car_pct"] = 100 - df_cars["car_owner_pct"]

# =========================
# 5. DISTRICT
# =========================
df_cars["district"] = "Barmbek-Süd"

# =========================
# 6. LONG FORMAT
# =========================
df_cars_long = df_cars.melt(
    id_vars=["year", "district"],
    value_vars=["car_owner_pct", "no_car_pct"],
    var_name="group",
    value_name="value"
)

# =========================
# 7. LABELS
# =========================
df_cars_long["group"] = df_cars_long["group"].replace({
    "car_owner_pct": "Car owners",
    "no_car_pct": "No car"
})

# =========================
# 8. EXPORT
# =========================
df_cars_long.to_csv(
    "../data/mart/mart_car_ownership.csv",
    index=False
)

print(df_cars_long.head())

   year     district       group  value
0  2024  Barmbek-Süd  Car owners   26.3
1  2023  Barmbek-Süd  Car owners   26.9
2  2022  Barmbek-Süd  Car owners   27.6
3  2021  Barmbek-Süd  Car owners   28.9
4  2020  Barmbek-Süd  Car owners   28.6

# Migraten im Stadtteil

In [87]:
import pandas as pd

# =========================
# 1. COPY
# =========================
df_migration = df_profile.copy()

# =========================
# 2. RENAME
# =========================
df_migration = df_migration.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung": "migration_pct"
})

# =========================
# 3. CLEAN
# =========================
df_migration["migration_pct"] = (
    df_migration["migration_pct"]
    .astype(str)
    .str.replace(",", ".")
    .astype(float)
)

# =========================
# 4. NON-MIGRATION
# =========================
df_migration["no_migration_pct"] = 100 - df_migration["migration_pct"]

# =========================
# 5. DISTRICT
# =========================
df_migration["district"] = "Barmbek-Süd"

# =========================
# 6. LONG FORMAT
# =========================
df_migration_long = df_migration.melt(
    id_vars=["year", "district"],
    value_vars=["migration_pct", "no_migration_pct"],
    var_name="group",
    value_name="value"
)

# =========================
# 7. LABELS
# =========================
df_migration_long["group"] = df_migration_long["group"].replace({
    "migration_pct": "With migration background",
    "no_migration_pct": "Without migration background"
})

# =========================
# 8. EXPORT
# =========================
df_migration_long.to_csv(
    "../data/mart/mart_migration_structure.csv",
    index=False
)

print(df_migration_long.head())

   year     district                      group  value
0  2024  Barmbek-Süd  With migration background   34.3
1  2023  Barmbek-Süd  With migration background   33.6
2  2022  Barmbek-Süd  With migration background   32.4
3  2021  Barmbek-Süd  With migration background   29.7
4  2020  Barmbek-Süd  With migration background   28.8

# Nur 1 Berichtsjahr

In [88]:
df_profile_small = df_profile[[
    "Berichtsjahr_Jahr",
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen",
    "Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren",
    "Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren"
]]

In [89]:
print(df_profile.head())
print(df_profile.columns)
print(df_profile.info())

   Berichtsjahr_Jahr  Bevölkerung und Haushalte_Anzahl der Einwohner: innen  \
0               2024                                              37091
1               2023                                              36705
2               2022                                              36452
3               2021                                              35709
4               2020                                              35880

   Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren  \
0                                               4096
1                                               4078
2                                               4077
3                                               3886
4                                               3906

   Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung  \
0                                               11.0
1                                               11.1
2                                               11.2
3                                               10.9
4                                               10.9

   Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren  \
0                                               5057
1                                               5004
2                                               5020
3                                               4976
4                                               5012

   Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung  \
0                                               13.6
1                                               13.6
2                                               13.8
3                                               13.9
4                                               14.0

   Bevölkerung und Haushalte_Anzahl ausländischer Einwohner: innen  \
0                                               6819
1                                               6603
2                                               6264
3                                               5261
4                                               5096

   Bevölkerung und Haushalte_Anteil ausländischer Einwohner: innen an der Gesamt-bevölkerung  \
0                                               18.4
1                                               18.0
2                                               17.2
3                                               14.7
4                                               14.2

   Bevölkerung und Haushalte_Anzahl der Einwohner: innen mit Migrations-hintergrund  \
0                                              12704
1                                              12315
2                                              11809
3                                              10609
4                                              10331

   Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung  \
0                                               34.3
1                                               33.6
2                                               32.4
3                                               29.7
4                                               28.8

   ...  \
0  ...
1  ...
2  ...
3  ...
4  ...

   Infrastruktur und Verkehr_Anzahl der Schüler:innen der Sekundarstufe I (nach Wohnort)  \
0                                               1107
1                                               1107
2                                               1057
3                                                978
4                                                977

   Infrastruktur und Verkehr_Anteil der Schüler:innen in Stadtteil-schulen an allen Schüler:innen der Sekundarstufe I (nach Wohnort)  \
0                                               51.6
1                                               52.1
2                                               50.1
3                                               50.6
4                                               50.7

   Infrastruktur und Verkehr_Anteil der Schüler:innen in Gymnasien an allen Schüler:innen der Sekundarstufe I (nach Wohnort)  \
0                                               45.9
1                                               45.1
2                                               47.2
3                                               46.5
4                                               46.3

   Infrastruktur und Verkehr_Anzahl der nieder-gelassenen Ärztinnen/Ärzte  \
0                                                 65
1                                                 61
2                                                 54
3                                                 51
4                                                 52

   Infrastruktur und Verkehr_Anzahl der Allgemein-ärztinnen/-ärzte  \
0                                                 21
1                                                 21
2                                                 15
3                                                 14
4                                                 15

   Infrastruktur und Verkehr_Anzahl der Zahn-ärztinnen/-ärzte  \
0                                                 29
1                                                 27
2                                                 25
3                                                 25
4                                                 27

   Infrastruktur und Verkehr_Anzahl der Apotheken  \
0                                               6
1                                               6
2                                               6
3                                               6
4                                               6

   Infrastruktur und Verkehr_Anzahl privater PKW  \
0                                           9746
1                                           9885
2                                          10073
3                                          10332
4                                          10259

   Infrastruktur und Verkehr_Anzahl der privaten PKW je 1 000 Einwohner: innen  \
0                                              263.0
1                                              269.0
2                                              276.0
3                                              289.0
4                                              286.0

   Infrastruktur und Verkehr_Anzahl Elektro-PKW
0                                         587.0
1                                         812.0
2                                         675.0
3                                         333.0
4                                         251.0

[5 rows x 69 columns]
Index(['Berichtsjahr_Jahr',
       'Bevölkerung und Haushalte_Anzahl der Einwohner: innen',
       'Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren',
       'Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren',
       'Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl ausländischer Einwohner: innen',
       'Bevölkerung und Haushalte_Anteil ausländischer Einwohner: innen an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl der Einwohner: innen mit Migrations-hintergrund',
       'Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung',
       'Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren mit Migrations-hintergrund',
       'Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren mit Migrations-hintergrund an allen Kindern und Jugendlichen unter 18 Jahren',
       'Bevölkerung und Haushalte_Anzahl der Haushalte',
       'Bevölkerung und Haushalte_Durch-schnittliche Anzahl der Personen je Haushalt',
       'Bevölkerung und Haushalte_Anzahl der Einpersonen-haushalte',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen nur eine Person lebt, an allen Haushalten',
       'Bevölkerung und Haushalte_Anzahl der Haushalte mit Kindern',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen Kinder leben, an allen Haushalten',
       'Bevölkerung und Haushalte_Anzahl der Haushalte, in denen Allein-erziehende leben',
       'Bevölkerung und Haushalte_Anteil der Haushalte, in denen Allein-erziehende leben, an allen Haushalten mit Kindern',
       'Bevölkerung und Haushalte_Fläche in km²',
       'Bevölkerung und Haushalte_Einwohner: innen je km²',
       'Bevölkerungsbewegung_Anzahl der Lebend-geborenen',
       'Bevölkerungsbewegung_Anzahl der Sterbefälle',
       'Bevölkerungsbewegung_Zuzüge über die Stadtteilgrenze pro Jahr',
       'Bevölkerungsbewegung_Fortzüge über die Stadtteilgrenze pro Jahr',
       'Bevölkerungsbewegung_Differenz der Zuzüge und Fortzüge über die Stadtteilgrenze',
       'Sozialstruktur_Sozial-versicherungs-pflichtig Beschäftigte am Wohnort',
       'Sozialstruktur_Anteil sozial-versicherungs-pflichtig Beschäftigter am Wohnort an den Erwerbs-fähigen (15 bis unter 65-Jährige)',
       'Sozialstruktur_Anzahl der Arbeitslosen',
       'Sozialstruktur_Anteil der Arbeitslosen an den Erwerbs-fähigen (15 bis unter 65-Jährige)',
       'Sozialstruktur_Jüngere Arbeitslose im Alter von 15 bis unter 25 Jahren',
       'Sozialstruktur_Anteil jüngerer Arbeitsloser (15 bis unter 25-Jährige) an den jüngeren Erwerbs-fähigen (15 bis unter 25-Jährige)',
       'Sozialstruktur_Ältere Arbeitslose im Alter von 55 bis unter 65 Jahren',
       'Sozialstruktur_Anteil älterer Arbeitsloser (55 bis unter 65-Jährige) an den älteren Erwerbs-fähigen (55 bis unter 65-Jährige)',
       'Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II',
       'Sozialstruktur_Anteil der Leistungs-empfänger: innen nach SGB II an der Gesamt-bevölkerung',
       'Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II unter 15 Jahren',
       'Sozialstruktur_Anteil der Leistungs-empfänger: innen nach SGB II unter 15 Jahren an der Bevölkerung unter 15 Jahren',
       'Sozialstruktur_Anzahl der Bedarfs-gemein-schaften nach SGB II',
       'Sozialstruktur_Empfänger:innen von Grund-sicherung im Alter der 65-Jährigen und Älteren',
       'Sozialstruktur_in % der 65-Jährigen und Älteren',
       'Sozialstruktur_Einkommen je Steuer-pflichtigen in Euro',
       'Wohnen_Anzahl der Wohngebäude', 'Wohnen_Anzahl der Wohnungen',
       'Wohnen_Anzahl der bezugsfertig gewordenen Wohnungen im Jahr',
       'Wohnen_Anzahl der Wohnungen in Ein- und Zweifamilien-häusern',
       'Wohnen_Anteil der Wohnungen in Ein- und Zweifamilien-häusern an allen Wohnungen',
       'Wohnen_Durch-schnittliche Wohnungs-größe in m²',
       'Wohnen_Durch-schnittliche Wohnfläche je Einwohner:in in m²',
       'Wohnen_Anzahl der Sozial-wohnungen',
       'Wohnen_Anteil der Sozial-wohnungen an allen Wohnungen',
       'Wohnen_Anzahl der Sozial-wohnungen mit Bindungs-auslauf bis 2029',
       'Wohnen_Anteil der Sozial-wohnungen mit Bindungs-auslauf bis 2029 an allen Sozial-wohnungen',
       'Wohnen_Durch-schnittlicher Immobilien-preis für ein Grundstück in EUR/m²',
       'Wohnen_Durch-schnittlicher Immobilien-preis für ein Ein- bzw Zweifamilien-haus in EUR/m²',
       'Wohnen_Durch-schnittlicher Immobilien-preis für eine Eigentums-wohnung in EUR/m²',
       'Infrastruktur und Verkehr_Kindergärten und Vorschul-klassen für Kinder im Alter von 3 Jahren bis Schuleintritt',
       'Infrastruktur und Verkehr_Anzahl der Grundschulen',
       'Infrastruktur und Verkehr_Anzahl der Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anteil der Schüler:innen in Stadtteil-schulen an allen Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anteil der Schüler:innen in Gymnasien an allen Schüler:innen der Sekundarstufe I (nach Wohnort)',
       'Infrastruktur und Verkehr_Anzahl der nieder-gelassenen Ärztinnen/Ärzte',
       'Infrastruktur und Verkehr_Anzahl der Allgemein-ärztinnen/-ärzte',
       'Infrastruktur und Verkehr_Anzahl der Zahn-ärztinnen/-ärzte',
       'Infrastruktur und Verkehr_Anzahl der Apotheken',
       'Infrastruktur und Verkehr_Anzahl privater PKW',
       'Infrastruktur und Verkehr_Anzahl der privaten PKW je 1 000 Einwohner: innen',
       'Infrastruktur und Verkehr_Anzahl Elektro-PKW'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 69 columns):
 #   Column                                                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                                                 --------------  -----
 0   Berichtsjahr_Jahr                                                                                                                                      12 non-null     int64
 1   Bevölkerung und Haushalte_Anzahl der Einwohner: innen                                                                                                  12 non-null     int64
 2   Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren                                                                           12 non-null     int64
 3   Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren an der Gesamt-bevölkerung                                                     12 non-null     float64
 4   Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren                                                                               12 non-null     int64
 5   Bevölkerung und Haushalte_Anteil älterer Einwohner: innen über 64 Jahren an der Gesamt-bevölkerung                                                     12 non-null     float64
 6   Bevölkerung und Haushalte_Anzahl ausländischer Einwohner: innen                                                                                        12 non-null     int64
 7   Bevölkerung und Haushalte_Anteil ausländischer Einwohner: innen an der Gesamt-bevölkerung                                                              12 non-null     float64
 8   Bevölkerung und Haushalte_Anzahl der Einwohner: innen mit Migrations-hintergrund                                                                       12 non-null     int64
 9   Bevölkerung und Haushalte_Anteil der Einwohner: innen mit Migrations-hintergrund an der Gesamt-bevölkerung                                             12 non-null     float64
 10  Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren mit Migrations-hintergrund                                                12 non-null     int64
 11  Bevölkerung und Haushalte_Anteil Kinder und Jugendlicher unter 18 Jahren mit Migrations-hintergrund an allen Kindern und Jugendlichen unter 18 Jahren  12 non-null     float64
 12  Bevölkerung und Haushalte_Anzahl der Haushalte                                                                                                         12 non-null     int64
 13  Bevölkerung und Haushalte_Durch-schnittliche Anzahl der Personen je Haushalt                                                                           12 non-null     float64
 14  Bevölkerung und Haushalte_Anzahl der Einpersonen-haushalte                                                                                             12 non-null     int64
 15  Bevölkerung und Haushalte_Anteil der Haushalte, in denen nur eine Person lebt, an allen Haushalten                                                     12 non-null     float64
 16  Bevölkerung und Haushalte_Anzahl der Haushalte mit Kindern                                                                                             12 non-null     int64
 17  Bevölkerung und Haushalte_Anteil der Haushalte, in denen Kinder leben, an allen Haushalten                                                             12 non-null     float64
 18  Bevölkerung und Haushalte_Anzahl der Haushalte, in denen Allein-erziehende leben                                                                       12 non-null     int64
 19  Bevölkerung und Haushalte_Anteil der Haushalte, in denen Allein-erziehende leben, an allen Haushalten mit Kindern                                      12 non-null     float64
 20  Bevölkerung und Haushalte_Fläche in km²                                                                                                                12 non-null     float64
 21  Bevölkerung und Haushalte_Einwohner: innen je km²                                                                                                      12 non-null     float64
 22  Bevölkerungsbewegung_Anzahl der Lebend-geborenen                                                                                                       12 non-null     int64
 23  Bevölkerungsbewegung_Anzahl der Sterbefälle                                                                                                            12 non-null     int64
 24  Bevölkerungsbewegung_Zuzüge über die Stadtteilgrenze pro Jahr                                                                                          12 non-null     object
 25  Bevölkerungsbewegung_Fortzüge über die Stadtteilgrenze pro Jahr                                                                                        12 non-null     object
 26  Bevölkerungsbewegung_Differenz der Zuzüge und Fortzüge über die Stadtteilgrenze                                                                        12 non-null     int64
 27  Sozialstruktur_Sozial-versicherungs-pflichtig Beschäftigte am Wohnort                                                                                  12 non-null     object
 28  Sozialstruktur_Anteil sozial-versicherungs-pflichtig Beschäftigter am Wohnort an den Erwerbs-fähigen (15 bis unter 65-Jährige)                         12 non-null     float64
 29  Sozialstruktur_Anzahl der Arbeitslosen                                                                                                                 12 non-null     object
 30  Sozialstruktur_Anteil der Arbeitslosen an den Erwerbs-fähigen (15 bis unter 65-Jährige)                                                                12 non-null     float64
 31  Sozialstruktur_Jüngere Arbeitslose im Alter von 15 bis unter 25 Jahren                                                                                 12 non-null     int64
 32  Sozialstruktur_Anteil jüngerer Arbeitsloser (15 bis unter 25-Jährige) an den jüngeren Erwerbs-fähigen (15 bis unter 25-Jährige)                        12 non-null     float64
 33  Sozialstruktur_Ältere Arbeitslose im Alter von 55 bis unter 65 Jahren                                                                                  12 non-null     int64
 34  Sozialstruktur_Anteil älterer Arbeitsloser (55 bis unter 65-Jährige) an den älteren Erwerbs-fähigen (55 bis unter 65-Jährige)                          12 non-null     float64
 35  Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II                                                                                       12 non-null     object
 36  Sozialstruktur_Anteil der Leistungs-empfänger: innen nach SGB II an der Gesamt-bevölkerung                                                             12 non-null     float64
 37  Sozialstruktur_Anzahl der Leistungs-empfänger: innen nach SGB II unter 15 Jahren                                                                       12 non-null     int64

In [90]:
print(df_profile_small.head())
print(df_profile_small.columns)
print(df_profile_small.info())

   Berichtsjahr_Jahr  Bevölkerung und Haushalte_Anzahl der Einwohner: innen  \
0               2024                                              37091
1               2023                                              36705
2               2022                                              36452
3               2021                                              35709
4               2020                                              35880

   Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren  \
0                                               4096
1                                               4078
2                                               4077
3                                               3886
4                                               3906

   Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren
0                                               5057
1                                               5004
2                                               5020
3                                               4976
4                                               5012
Index(['Berichtsjahr_Jahr',
       'Bevölkerung und Haushalte_Anzahl der Einwohner: innen',
       'Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren',
       'Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   Berichtsjahr_Jahr                                                             12 non-null     int64
 1   Bevölkerung und Haushalte_Anzahl der Einwohner: innen                         12 non-null     int64
 2   Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren  12 non-null     int64
 3   Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren      12 non-null     int64
dtypes: int64(4)
memory usage: 516.0 bytes
None

In [91]:
df_profile_small["Berichtsjahr_Jahr"] = pd.to_numeric(
    df_profile_small["Berichtsjahr_Jahr"], errors="coerce"
)

In [92]:
df_profile_latest = df_profile_small[df_profile_small["Berichtsjahr_Jahr"] == 2024]

# Für sociodemografische Eckdaten über Stadtteil

In [93]:
df_pop = df_profile.copy()

df_pop = df_pop.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen": "population"
})

df_pop_trend = df_pop[["year", "population"]]

df_pop_trend.to_csv("../data/mart/mart_population_trend.csv", index=False)

In [94]:
df_pop = df_profile.copy()

df_pop = df_pop.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen": "population",
    "Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren": "children",
    "Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren": "elderly"
})

# district hinzufügen
df_pop["district"] = "Barmbek-Süd"

# Long Format
df_long = df_pop.melt(
    id_vars=["year", "district"],
    value_vars=["population", "children", "elderly"],
    var_name="group",
    value_name="value"
)

df_long["group"] = df_long["group"].replace({
    "population": "Total Population",
    "children": "Children (<18)",
    "elderly": "Elderly (65+)"
})

# Export
df_long.to_csv("../data/mart/mart_population_long.csv", index=False)

In [95]:
df_long.head()

   year     district             group  value
0  2024  Barmbek-Süd  Total Population  37091
1  2023  Barmbek-Süd  Total Population  36705
2  2022  Barmbek-Süd  Total Population  36452
3  2021  Barmbek-Süd  Total Population  35709
4  2020  Barmbek-Süd  Total Population  35880

# Zu Einwohnerzahl Spalte district hinzufügen, damit Verbindung zu Geodaten

In [96]:
df_profile_latest["district"] = "Barmbek-Süd"

# Merge of geadata and socio data

# Again load all prep geojsons

In [97]:

# Transport & Infrastruktur
gdf_stops = gpd.read_file(PATH_RAW + "prep_public_transport_barmbek.geojson")
gdf_crossings = gpd.read_file(PATH_RAW + "prep_crossings_barmbek.geojson")
gdf_bike = gpd.read_file(PATH_RAW + "prep_bikelane_barmbek.geojson")

gdf_bike_proj = gdf_bike.to_crs(epsg=25832)

bike_length_km = gdf_bike_proj.length.sum() / 1000

# Grün & Umwelt
gdf_green = gpd.read_file(PATH_RAW + "prep_green_barmbek.geojson")
gdf_park = gpd.read_file(PATH_RAW + "prep_park_barmbek.geojson")
gdf_greenplan = gpd.read_file(PATH_RAW + "prep_greenplan_barmbek.geojson")

# Mobilität
gdf_stadtrad = gpd.read_file(PATH_RAW + "prep_stadtrad_barmbek.geojson")
gdf_emobility = gpd.read_file(PATH_RAW + "prep_emobility_barmbek.geojson")

# Verkehr & Straßen
gdf_streets = gpd.read_file(PATH_RAW + "prep_streets_cover_barmbek.geojson")
gdf_highway = gpd.read_file(PATH_RAW + "prep_highway_barmbek.geojson")
gdf_crosswalks = gpd.read_file(PATH_RAW + "prep_fussgaengerueberwege_barmbek.geojson")

# Sonstiges
gdf_switch = gpd.read_file(PATH_RAW + "prep_switch_barmbek.geojson")
gdf_lsa = gpd.read_file(PATH_RAW + "prep_lsa_barmbek.geojson")

In [98]:
pt_stops = len(gdf_stops)
crossings = len(gdf_crossings)
stadtrad = len(gdf_stadtrad)
emobility = len(gdf_emobility)
lsa = len(gdf_lsa)
street_segments = len(gdf_streets)

green_area = float(gdf_greenplan["FLAECHE_QM"].sum())
bike_km = float(bike_length_km)

In [99]:
import pandas as pd

df_geo = pd.DataFrame([{
    "district": "Barmbek-Süd",
    "pt_stops": pt_stops,
    "crossings": crossings,
    "stadtrad": stadtrad,
    "emobility": emobility,
    "lsa": lsa,
    "green_area_m2": green_area,
    "street_segments": street_segments,
    "bike_km": bike_km
}])

## Check of both tables

In [100]:
df_geo.head()

,district,pt_stops,crossings,stadtrad,emobility,lsa,green_area_m2,street_segments,bike_km
0,Barmbek-Süd,19,15,10,20,27,311652.0,520,12.042108

In [101]:
df_profile_latest.head()

,Berichtsjahr_Jahr,Bevölkerung und Haushalte_Anzahl der Einwohner: innen,Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren,Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren,district
0,2024,37091,4096,5057,Barmbek-Süd

# Merge

In [102]:
df_final = df_geo.merge(
    df_profile_latest,
    on="district",
    how="left"
)

In [103]:
df_final.head()

,district,pt_stops,crossings,stadtrad,emobility,lsa,green_area_m2,street_segments,bike_km,Berichtsjahr_Jahr,Bevölkerung und Haushalte_Anzahl der Einwohner: innen,Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren,Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren
0,Barmbek-Süd,19,15,10,20,27,311652.0,520,12.042108,2024,37091,4096,5057

In [104]:
df_final.rename(columns={
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen": "population",
    "Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren": "children",
    "Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren": "elderly"
}, inplace=True)

In [105]:
df_final.to_csv("../data/mart/walkability_data_mart.csv", index=False, sep=";")

# Walkability Score nach Chatjpt

## Normalize all data, because they are in different scales

In [106]:
df_score = df_final.copy()

df_score["pt_stops_norm"] = df_score["pt_stops"] / df_score["pt_stops"].max()
df_score["crossings_norm"] = df_score["crossings"] / df_score["crossings"].max()
df_score["stadtrad_norm"] = df_score["stadtrad"] / df_score["stadtrad"].max()
df_score["emobility_norm"] = df_score["emobility"] / df_score["emobility"].max()
df_score["green_norm"] = df_score["green_area_m2"] / df_score["green_area_m2"].max()
df_score["bike_norm"] = df_score["bike_km"] / df_score["bike_km"].max()

## Count the score

In [107]:
df_score["walkability_score"] = (
    df_score["pt_stops_norm"] +
    df_score["crossings_norm"] +
    df_score["stadtrad_norm"] +
    df_score["emobility_norm"] +
    df_score["green_norm"] +
    df_score["bike_norm"]
) / 6

## Check

In [108]:
df_score[["district", "walkability_score"]]

      district  walkability_score
0  Barmbek-Süd                1.0

In [109]:
df_final.to_csv("../data/mart/walkability_data_mart.csv", index=False)

In [110]:
df_final.head()

,district,pt_stops,crossings,stadtrad,emobility,lsa,green_area_m2,street_segments,bike_km,Berichtsjahr_Jahr,population,children,elderly
0,Barmbek-Süd,19,15,10,20,27,311652.0,520,12.042108,2024,37091,4096,5057

# Age Structure

In [111]:
df_age = df_profile.copy()

df_age = df_age.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen": "population",
    "Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren": "children",
    "Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren": "elderly"
})

# Nur letztes Jahr nehmen (für klare Aussage)
df_latest = df_age.sort_values("year", ascending=False).head(1)

df_age_structure = pd.DataFrame({
    "group": ["Children (<18)", "Elderly (65+)", "Others"],
    "value": [
        df_latest["children"].values[0],
        df_latest["elderly"].values[0],
        df_latest["population"].values[0]
        - df_latest["children"].values[0]
        - df_latest["elderly"].values[0]
    ]
})

df_age_structure.to_csv("../data/mart/mart_age_structure.csv", index=False)

In [112]:
import pandas as pd

# =========================
# COPY SOURCE DATA
# =========================
df_age = df_profile.copy()

# =========================
# RENAME COLUMNS
# =========================
df_age = df_age.rename(columns={
    "Berichtsjahr_Jahr": "year",
    "Bevölkerung und Haushalte_Anzahl der Einwohner: innen": "population",
    "Bevölkerung und Haushalte_Anzahl der Kinder und Jugendlichen unter 18 Jahren": "children",
    "Bevölkerung und Haushalte_Anzahl älterer Einwohner: innen über 64 Jahren": "elderly"
})

# =========================
# KEEP ONLY RELEVANT COLUMNS
# =========================
df_age = df_age[[
    "year",
    "population",
    "children",
    "elderly"
]].dropna()

# =========================
# BUILD LONG FORMAT (ALL YEARS)
# =========================
rows = []

for _, row in df_age.iterrows():
    
    # Children
    rows.append({
        "year": row["year"],
        "group": "Children (<18)",
        "value": row["children"]
    })

    # Elderly
    rows.append({
        "year": row["year"],
        "group": "Elderly (65+)",
        "value": row["elderly"]
    })

    # Others
    rows.append({
        "year": row["year"],
        "group": "Others",
        "value": row["population"] - row["children"] - row["elderly"]
    })

# =========================
# FINAL DATAFRAME
# =========================
df_age_structure = pd.DataFrame(rows)

# =========================
# SORT (OPTIONAL)
# =========================
df_age_structure = df_age_structure.sort_values(
    by=["year", "group"]
)

# =========================
# EXPORT
# =========================
df_age_structure.to_csv(
    "../data/mart/mart_age_structure.csv",
    index=False
)

# =========================
# CHECK
# =========================
print(df_age_structure.head(15))
print(df_age_structure["year"].unique())

    year           group  value
33  2013  Children (<18)   3105
34  2013   Elderly (65+)   5100
35  2013          Others  24577
30  2014  Children (<18)   3183
31  2014   Elderly (65+)   5092
32  2014          Others  24841
27  2015  Children (<18)   3353
28  2015   Elderly (65+)   5097
29  2015          Others  25231
24  2016  Children (<18)   3625
25  2016   Elderly (65+)   5058
26  2016          Others  26109
21  2017  Children (<18)   3703
22  2017   Elderly (65+)   4992
23  2017          Others  26523
[2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

# Bike lane

In [113]:
import pandas as pd
import geopandas as gpd

# =========================
# 1. LOAD
# =========================
gdf = gpd.read_file("../data/prep/prep_bikelane_barmbek.geojson")

# =========================
# 2. CLEAN
# =========================
# Länge in km
gdf["length_km"] = gdf["laenge"] / 1000

# =========================
# 3. AGGREGATE
# =========================
df_bike = gdf.groupby("status")["length_km"].sum().reset_index()

# =========================
# 4. ADD CONTEXT
# =========================
df_bike["district"] = "Barmbek-Süd"
df_bike["year"] = 2024

# =========================
# 5. RENAME
# =========================
df_bike = df_bike.rename(columns={
    "status": "category",
    "length_km": "value"
})

# 6. EXPORT
# =========================
df_bike.to_csv(
    "../data/mart/mart_bike_barmbek.csv",
    index=False
)

print(df_bike)

                              category  value     district  year
0                             Existing  6.002  Barmbek-Süd  2024
1        Priority network improvements  6.315  Barmbek-Süd  2024
2  Sections with improvement potential  0.023  Barmbek-Süd  2024
3                   Under construction  3.944  Barmbek-Süd  2024

In [114]:
print(df_bike["category"].unique())

<StringArray>
[                           'Existing',       'Priority network improvements',
 'Sections with improvement potential',                  'Under construction']
Length: 4, dtype: str

# Greenplan

In [115]:
import pandas as pd
import geopandas as gpd

# LOAD
gdf = gpd.read_file("../data/prep/prep_greenplan_barmbek.geojson")

# AGGREGATE
df_green_summary = (
    gdf.groupby("green_type")["FLAECHE_QM"]
    .sum()
    .reset_index()
)

# KM²
df_green_summary["value"] = df_green_summary["FLAECHE_QM"] / 1_000_000

df_green_summary["value"] = gdf.groupby("green_type")["FLAECHE_QM"].sum().values

# CLEAN
df_green_summary = df_green_summary.rename(columns={
    "green_type": "category"
})

df_green_summary["district"] = "Barmbek-Süd"
df_green_summary["year"] = 2024

df_green_summary["value"] = (
    df_green_summary["FLAECHE_QM"] /
    df_green_summary["FLAECHE_QM"].sum()
)

# EXPORT
df_green_summary.to_csv(
    "../data/mart/mart_green_barmbek.csv",
    index=False
)

print(df_green_summary)

           category  FLAECHE_QM     value     district  year
0  Allotment garden        5135  0.016477  Barmbek-Süd  2024
1         Other use        5924  0.019008  Barmbek-Süd  2024
2              Park      213046  0.683602  Barmbek-Süd  2024
3        Playground       87547  0.280913  Barmbek-Süd  2024

# Streets cover mart

In [116]:
import geopandas as gpd
import pandas as pd

# =========================
# LOAD
# =========================
streets = gpd.read_file("../data/prep/prep_streets_cover_barmbek.geojson")

# =========================
# SELECT
# =========================
streets = streets[[
    "wegeart",
    "fahrstreifenanzahl_in_beide_richtungen",
    "geschwindigkeit",
    "strassendeckschicht",
    "geometry"
]].dropna()

# =========================
# RENAME
# =========================
streets = streets.rename(columns={
    "wegeart": "road_type",
    "fahrstreifenanzahl_in_beide_richtungen": "lanes",
    "geschwindigkeit": "speed_raw",
    "strassendeckschicht": "surface_type"
})

# =========================
# SPEED CLEAN
# =========================
streets["speed_kmh"] = (
    streets["speed_raw"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

# =========================
# SURFACE CLEAN
# =========================
streets["surface_type_clean"] = streets["surface_type"].astype(str)

streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Asphaltbetone.*", "Asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Offenporiger Asphalt.*", "Porous asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Splittmastixasphalt.*", "Stone mastic asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Gussasphalt.*", "Mastic asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Pflaster.*", "Paving stones", regex=True)

# =========================
# WALKABILITY SCORE (NEU & KLAR)
# =========================
def calc_walkability(row):
    score = 0

    # SPEED (stark gewichtet)
    if row["speed_kmh"] <= 30:
        score += 3
    elif row["speed_kmh"] <= 40:
        score += 1
    else:
        score -= 2

    # LANES (breite Straßen schlechter)
    if row["lanes"] <= 2:
        score += 2
    elif row["lanes"] == 3:
        score += 0
    else:
        score -= 2

    # SURFACE (entscheidend)
    if row["surface_type_clean"] in ["Asphalt", "Porous asphalt"]:
        score += 2
    elif row["surface_type_clean"] == "Stone mastic asphalt":
        score += 1
    elif row["surface_type_clean"] == "Mastic asphalt":
        score += 0
    elif row["surface_type_clean"] == "Paving stones":
        score -= 3   # ❗ bewusst stark negativ
    else:
        score -= 1

    return score

streets["walkability_score"] = streets.apply(calc_walkability, axis=1)

# =========================
# CLASSIFICATION (NUR EINMAL!)
# =========================
def classify_walkability(score):
    if score >= 4:
        return "High walkability"
    elif score >= 1:
        return "Medium walkability"
    else:
        return "Low walkability"

streets["walkability_class"] = streets["walkability_score"].apply(classify_walkability)

# =========================
# CONTEXT
# =========================
streets["district"] = "Barmbek-Süd"
streets["year"] = 2024

# =========================
# FINAL
# =========================
streets_mart = streets[[
    "geometry",
    "road_type",
    "surface_type_clean",
    "speed_kmh",
    "lanes",
    "walkability_score",
    "walkability_class",
    "district",
    "year"
]]

# =========================
# EXPORT
# =========================
streets_mart.to_file(
    "../data/mart/mart_street_walkability.geojson",
    driver="GeoJSON"
)

# =========================
# CHECK
# =========================
print(streets_mart["walkability_class"].value_counts())

walkability_class
Medium walkability    250
High walkability      239
Low walkability        30
Name: count, dtype: int64

In [117]:
import geopandas as gpd
import pandas as pd

# =========================
# LOAD
# =========================
streets = gpd.read_file("../data/prep/prep_streets_cover_barmbek.geojson")

# =========================
# SELECT
# =========================
streets = streets[[
    "wegeart",
    "fahrstreifenanzahl_in_beide_richtungen",
    "geschwindigkeit",
    "strassendeckschicht",
    "geometry"
]].dropna()

# =========================
# RENAME
# =========================
streets = streets.rename(columns={
    "wegeart": "road_type",
    "fahrstreifenanzahl_in_beide_richtungen": "lanes",
    "geschwindigkeit": "speed_raw",
    "strassendeckschicht": "surface_type"
})

# =========================
# SPEED CLEAN
# =========================
streets["speed_kmh"] = (
    streets["speed_raw"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

# =========================
# SURFACE CLEAN
# =========================
streets["surface_type_clean"] = streets["surface_type"].astype(str)

streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Asphaltbetone.*", "Asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Offenporiger Asphalt.*", "Porous asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Splittmastixasphalt.*", "Stone mastic asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Gussasphalt.*", "Mastic asphalt", regex=True)
streets["surface_type_clean"] = streets["surface_type_clean"].str.replace(r".*Pflaster.*", "Paving stones", regex=True)

# =========================
# WALKABILITY SCORE (0–7)
# =========================
def calc_walkability(row):
    score = 0

    # SPEED
    if row["speed_kmh"] <= 30:
        score += 3
    elif row["speed_kmh"] <= 40:
        score += 2
    else:
        score += 0

    # LANES
    if row["lanes"] <= 2:
        score += 2
    elif row["lanes"] == 3:
        score += 1
    else:
        score += 0

    # SURFACE
    if row["surface_type_clean"] in ["Asphalt", "Porous asphalt"]:
        score += 2
    elif row["surface_type_clean"] == "Stone mastic asphalt":
        score += 1
    elif row["surface_type_clean"] == "Paving stones":
        score += 0
    else:
        score += 1

    return score

streets["walkability_score"] = streets.apply(calc_walkability, axis=1)

# =========================
# CLASSIFICATION
# =========================
def classify_walkability(score):
    if score >= 5:
        return "High walkability"
    elif score >= 3:
        return "Medium walkability"
    else:
        return "Low walkability"

streets["walkability_class"] = streets["walkability_score"].apply(classify_walkability)

# =========================
# CONTEXT
# =========================
streets["district"] = "Barmbek-Süd"
streets["year"] = 2024

# =========================
# FINAL
# =========================
streets_mart = streets[[
    "geometry",
    "road_type",
    "surface_type_clean",
    "speed_kmh",
    "lanes",
    "walkability_score",
    "walkability_class",
    "district",
    "year"
]]

# =========================
# EXPORT
# =========================
streets_mart.to_file(
    "../data/mart/mart_street_walkability.geojson",
    driver="GeoJSON"
)

# =========================
# CHECK
# =========================
print(streets_mart["walkability_score"].describe())
print(streets_mart["walkability_class"].value_counts())

count    519.000000
mean       5.175337
std        1.765742
min        2.000000
25%        3.000000
50%        5.000000
75%        7.000000
max        7.000000
Name: walkability_score, dtype: float64
walkability_class
High walkability      320
Medium walkability    183
Low walkability        16
Name: count, dtype: int64

# Crossings von walkability score

In [118]:
import geopandas as gpd

# LOAD
gdf_streets = gpd.read_file("../data/mart/mart_street_walkability.geojson")
gdf_crossings = gpd.read_file("../data/prep/prep_crossings_barmbek.geojson")

# CRS angleichen (wichtig!)
gdf_crossings = gdf_crossings.to_crs(gdf_streets.crs)

# Spatial Join (nächste Straße finden)
gdf_crossings_joined = gpd.sjoin_nearest(
    gdf_crossings,
    gdf_streets[["geometry", "walkability_score", "walkability_class"]],
    how="left"
)

/opt/miniconda3/envs/python_neu_nicole_12012026/lib/python3.13/site-packages/geopandas/array.py:407: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(

In [119]:
gdf_crossings_joined.to_file(
    "../data/mart/mart_crossings_walkability.geojson",
    driver="GeoJSON"
)

# Final score streets + infrastructure from streets

In [120]:
import geopandas as gpd
import pandas as pd

# =========================
# LOAD DATA
# =========================
gdf_streets = gpd.read_file("../data/mart/mart_street_walkability.geojson")

gdf_crossings = gpd.read_file("../data/prep/prep_crossings_barmbek.geojson")
gdf_lsa = gpd.read_file("../data/prep/prep_lsa_barmbek.geojson")
gdf_switch = gpd.read_file("../data/prep/switch_barmbek.geojson")

# =========================
# CRS FIX (METERS!)
# =========================
TARGET_CRS = 25832  # UTM Hamburg

gdf_streets = gdf_streets.to_crs(TARGET_CRS)
gdf_crossings = gdf_crossings.to_crs(TARGET_CRS)
gdf_lsa = gdf_lsa.to_crs(TARGET_CRS)
gdf_switch = gdf_switch.to_crs(TARGET_CRS)

# =========================
# POINT TYPES
# =========================
gdf_crossings["type"] = "crossing"
gdf_lsa["type"] = "traffic_light"
gdf_switch["type"] = "mobility_hub"

# =========================
# MERGE POINTS
# =========================
gdf_points = pd.concat([
    gdf_crossings[["geometry", "type"]],
    gdf_lsa[["geometry", "type"]],
    gdf_switch[["geometry", "type"]]
], ignore_index=True)

gdf_points = gpd.GeoDataFrame(gdf_points, geometry="geometry", crs=TARGET_CRS)

# =========================
# INFRA SCORING (verbessert)
# =========================
def score_point(row):
    if row["type"] == "traffic_light":
        return 3
    elif row["type"] == "crossing":
        return 2
    elif row["type"] == "mobility_hub":
        return 4   # 🔥 stärker gewichtet
    else:
        return 1

gdf_points["infra_score"] = gdf_points.apply(score_point, axis=1)

# =========================
# STREET ID (wichtig!)
# =========================
gdf_streets = gdf_streets.reset_index().rename(columns={"index": "street_id"})

# =========================
# BUFFER (50m Einflussbereich)
# =========================
gdf_streets_buffer = gdf_streets.copy()
gdf_streets_buffer["geometry"] = gdf_streets_buffer.geometry.buffer(50)

# =========================
# SPATIAL JOIN (INTERSECTS)
# =========================
gdf_joined = gpd.sjoin(
    gdf_streets_buffer,
    gdf_points,
    how="left",
    predicate="intersects"
)

# =========================
# INFRA AGGREGATION (pro Straße)
# =========================
infra_per_street = (
    gdf_joined.groupby("street_id")["infra_score"]
    .sum()
    .reset_index()
)

# =========================
# MERGE BACK
# =========================
gdf_final = gdf_streets.merge(infra_per_street, on="street_id", how="left")

gdf_final["infra_score"] = gdf_final["infra_score"].fillna(0)

# =========================
# NORMALISIERUNG INFRA (0–5)
# =========================
gdf_final["infra_score_scaled"] = (
    gdf_final["infra_score"] / gdf_final["infra_score"].max()
) * 5

# =========================
# FINAL SCORE (0–10)
# =========================
gdf_final["final_score"] = (
    gdf_final["walkability_score"] +
    gdf_final["infra_score_scaled"]
)

# Normalisieren auf 0–10
gdf_final["final_score"] = (
    gdf_final["final_score"] - gdf_final["final_score"].min()
)

gdf_final["final_score"] = (
    gdf_final["final_score"] / gdf_final["final_score"].max()
) * 10

# =========================
# FINAL CLASS (optional)
# =========================
def classify_final(score):
    if score >= 7:
        return "High"
    elif score >= 4:
        return "Medium"
    else:
        return "Low"

gdf_final["final_class"] = gdf_final["final_score"].apply(classify_final)

# =========================
# EXPORT (WICHTIG!)
# =========================
gdf_final.to_file(
    "../data/mart/mart_walkability_with_infra.geojson",
    driver="GeoJSON"
)

# =========================
# DEBUG CHECKS
# =========================
print("Columns:", gdf_final.columns)
print("\nWalkability:")
print(gdf_final["walkability_score"].describe())

print("\nInfra:")
print(gdf_final["infra_score"].describe())

print("\nFinal:")
print(gdf_final["final_score"].describe())

print("\nSample:")
print(gdf_final.head())

Columns: Index(['street_id', 'road_type', 'surface_type_clean', 'speed_kmh', 'lanes',
       'walkability_score', 'walkability_class', 'district', 'year',
       'geometry', 'infra_score', 'infra_score_scaled', 'final_score',
       'final_class'],
      dtype='str')

Walkability:
count    519.000000
mean       5.175337
std        1.765742
min        2.000000
25%        3.000000
50%        5.000000
75%        7.000000
max        7.000000
Name: walkability_score, dtype: float64

Infra:
count    519.000000
mean       1.630058
std        2.327016
min        0.000000
25%        0.000000
50%        0.000000
75%        3.000000
max       15.000000
Name: infra_score, dtype: float64

Final:
count    519.000000
mean       4.131878
std        1.956730
min        0.000000
25%        2.222222
50%        4.074074
75%        5.555556
max       10.000000
Name: final_score, dtype: float64

Sample:
   street_id                                          road_type  \
0          0  Stadtstraße (alle Straßen, die nicht BAB oder ...
1          1  Stadtstraße (alle Straßen, die nicht BAB oder ...
2          2  Stadtstraße (alle Straßen, die nicht BAB oder ...
3          3  Stadtstraße (alle Straßen, die nicht BAB oder ...
4          4  Stadtstraße (alle Straßen, die nicht BAB oder ...

  surface_type_clean  speed_kmh  lanes  walkability_score walkability_class  \
0            Asphalt       30.0      0                  7  High walkability
1      Paving stones       30.0      0                  5  High walkability
2            Asphalt       30.0      0                  7  High walkability
3            Asphalt       30.0      0                  7  High walkability
4            Asphalt       30.0      0                  7  High walkability

      district  year                                           geometry  \
0  Barmbek-Süd  2024  LINESTRING (569339.339 5936492.957, 569336.149...
1  Barmbek-Süd  2024  LINESTRING (569336.149 5936501.685, 569329.452...
2  Barmbek-Süd  2024  LINESTRING (569139.08 5936499.57, 569147.227 5...
3  Barmbek-Süd  2024  LINESTRING (569329.313 5936520.723, 569326.661...
4  Barmbek-Süd  2024  LINESTRING (569326.661 5936529.92, 569325.085 ...

   infra_score  infra_score_scaled  final_score final_class
0          0.0                 0.0     5.555556      Medium
1          0.0                 0.0     3.333333         Low
2          0.0                 0.0     5.555556      Medium
3          0.0                 0.0     5.555556      Medium
4          0.0                 0.0     5.555556      Medium

In [121]:
print(gdf_final.geometry.geom_type.value_counts())

LineString         515
MultiLineString      4
Name: count, dtype: int64

In [122]:
pct = (
    streets_mart["walkability_class"]
    .value_counts(normalize=True)
    .mul(100)
    .round(1)
)

print(pct)

walkability_class
High walkability      61.7
Medium walkability    35.3
Low walkability        3.1
Name: proportion, dtype: float64

In [123]:
print(gdf_joined["infra_score"].describe())
print(gdf_joined["infra_score"].value_counts())

count    284.000000
mean       2.978873
std        0.634333
min        2.000000
25%        3.000000
50%        3.000000
75%        3.000000
max        4.000000
Name: infra_score, dtype: float64
infra_score
3.0    170
2.0     60
4.0     54
Name: count, dtype: int64

In [124]:
print(gdf_final.groupby("final_class")["final_score"].describe())

             count      mean       std       min       25%       50%  \
final_class
High          33.0  7.497194  0.674277  7.037037  7.037037  7.037037
Low          257.0  2.392276  0.974375  0.000000  2.222222  2.222222
Medium       229.0  5.599224  0.596709  4.074074  5.555556  5.555556

                  75%        max
final_class
High         7.777778  10.000000
Low          3.333333   3.703704
Medium       5.555556   6.666667

# Walkability mit Bodenrichtwerten

### LOAD

In [125]:
import geopandas as gpd

gdf_land_values_barmbek = gpd.read_file(
    "../data/prep/prep_land_values_barmbek.geojson"
)

In [126]:
print(gdf_final.crs)
print(gdf_land_values_barmbek.crs)

EPSG:25832
EPSG:25832

### Filtern nach Multi-family -housing

In [127]:
gdf_land_values_mfh = gdf_land_values_barmbek[
    gdf_land_values_barmbek["land_use_type"] == "Multi-family houses"
].copy()

## Spacial Join

In [128]:
gdf_walkability_with_land_values = gpd.sjoin(
    gdf_final,
    gdf_land_values_mfh[
        [
            "zone_id",
            "street_name",
            "land_value",
            "reference_date",
            "zone_name",
            "land_use_type",
            "geometry"
        ]
    ],
    how="left",
    predicate="intersects"
).drop(columns="index_right")

### CHECK

In [129]:
gdf_walkability_with_land_values["street_id"].value_counts().head(20)

street_id
108    7
183    7
363    7
80     6
342    6
350    6
371    6
468    6
510    6
15     5
44     5
71     5
81     5
83     5
94     5
102    5
184    5
188    5
191    5
242    5
Name: count, dtype: int64

In [130]:
gdf_walkability_with_land_values[
    gdf_walkability_with_land_values["street_id"] == 2
][[
    "street_id",
    "zone_id",
    "land_value",
    "land_use_type",
    "zone_name"
]]

,street_id,zone_id,land_value,land_use_type,zone_name
2,2,01227690,1951.93,Multi-family houses,V098;Von-Essen-Straße;59;;;Hamburg-Nord;51012;...
2,2,01227693,2249.82,Multi-family houses,L253;Lortzingstraße;6;;;Hamburg-Nord;51012;422024
2,2,01227694,2249.82,Multi-family houses,V098;Von-Essen-Straße;38;;;Hamburg-Nord;51012;...

In [131]:
print(gdf_walkability_with_land_values.columns.tolist())

['street_id', 'road_type', 'surface_type_clean', 'speed_kmh', 'lanes', 'walkability_score', 'walkability_class', 'district', 'year', 'geometry', 'infra_score', 'infra_score_scaled', 'final_score', 'final_class', 'zone_id', 'street_name', 'land_value', 'reference_date', 'zone_name', 'land_use_type']

In [132]:
gdf_walkability_with_land_values["land_use_type"].value_counts(dropna=False)

land_use_type
Multi-family houses    1075
NaN                      29
Name: count, dtype: int64

In [133]:
gdf_walkability_with_land_values["street_id"].value_counts().head(20)

street_id
108    7
183    7
363    7
80     6
342    6
350    6
371    6
468    6
510    6
15     5
44     5
71     5
81     5
83     5
94     5
102    5
184    5
188    5
191    5
242    5
Name: count, dtype: int64

In [134]:
gdf_walkability_with_land_values[
    gdf_walkability_with_land_values["street_id"] == 2
][[
    "street_id",
    "zone_id",
    "land_value",
    "land_use_type",
    "zone_name"
]]

,street_id,zone_id,land_value,land_use_type,zone_name
2,2,01227690,1951.93,Multi-family houses,V098;Von-Essen-Straße;59;;;Hamburg-Nord;51012;...
2,2,01227693,2249.82,Multi-family houses,L253;Lortzingstraße;6;;;Hamburg-Nord;51012;422024
2,2,01227694,2249.82,Multi-family houses,V098;Von-Essen-Straße;38;;;Hamburg-Nord;51012;...

### Median Bodenrichtwert pro Straßensegment errechnen

In [135]:
land_values_median = (
    gdf_walkability_with_land_values
    .groupby("street_id", as_index=False)
    .agg(
        land_value=("land_value", "median"),
        street_name=("street_name", "first")
    )
)

### Check Median

In [136]:
print(land_values_median.shape)
land_values_median.head()

(519, 3)

   street_id  land_value       street_name
0          0         NaN               NaN
1          1         NaN               NaN
2          2     2249.82  Von-Essen-Straße
3          3     2249.82    Lortzingstraße
4          4     2249.82    Lortzingstraße

### Combine Median with walkability

In [137]:
gdf_mart_walkability_land_values = gdf_final.merge(
    land_values_median,
    on="street_id",
    how="left"
)

### Check the merge

In [138]:
print(gdf_mart_walkability_land_values.shape)

gdf_mart_walkability_land_values.head()

(519, 16)

,street_id,road_type,surface_type_clean,speed_kmh,lanes,walkability_score,walkability_class,district,year,geometry,infra_score,infra_score_scaled,final_score,final_class,land_value,street_name
0,0,"Stadtstraße (alle Straßen, die nicht BAB oder ...",Asphalt,30.0,0,7,High walkability,Barmbek-Süd,2024,"LINESTRING (569339.339 5936492.957, 569336.149...",0.0,0.0,5.555556,Medium,NaN,NaN
1,1,"Stadtstraße (alle Straßen, die nicht BAB oder ...",Paving stones,30.0,0,5,High walkability,Barmbek-Süd,2024,"LINESTRING (569336.149 5936501.685, 569329.452...",0.0,0.0,3.333333,Low,NaN,NaN
2,2,"Stadtstraße (alle Straßen, die nicht BAB oder ...",Asphalt,30.0,0,7,High walkability,Barmbek-Süd,2024,"LINESTRING (569139.08 5936499.57, 569147.227 5...",0.0,0.0,5.555556,Medium,2249.82,Von-Essen-Straße
3,3,"Stadtstraße (alle Straßen, die nicht BAB oder ...",Asphalt,30.0,0,7,High walkability,Barmbek-Süd,2024,"LINESTRING (569329.313 5936520.723, 569326.661...",0.0,0.0,5.555556,Medium,2249.82,Lortzingstraße
4,4,"Stadtstraße (alle Straßen, die nicht BAB oder ...",Asphalt,30.0,0,7,High walkability,Barmbek-Süd,2024,"LINESTRING (569326.661 5936529.92, 569325.085 ...",0.0,0.0,5.555556,Medium,2249.82,Lortzingstraße

In [139]:
gdf_mart_walkability_land_values["land_value"].isna().sum()

np.int64(29)

In [140]:
gdf_mart_walkability_land_values["land_value"].describe()

count     490.000000
mean     2423.221612
std       938.359333
min       665.650000
25%      1800.000000
50%      2327.825000
75%      2830.260000
max      5849.840000
Name: land_value, dtype: float64

In [141]:
gdf_mart_walkability_land_values["street_id"].nunique()

519

### Save

In [142]:
gdf_mart_walkability_land_values.to_file(
    "../data/mart/mart_walkability_land_values.geojson",
    driver="GeoJSON"
)

### Aggregate multiple MFH land values per street segment
### using the median to obtain one representative
### land value for each street.

# PROOF OF CONCEPT: FINE MAPPING with gdf_final ID

In [143]:
import geopandas as gpd

gdf_proof_areas = gpd.read_file(
    "../data/raw/raw_data_geoportal/feinkartierung_strasse_json/de_hh_up_strassenflaechen_EPSG_4326.json"
)

In [144]:
gdf_final.columns

Index(['street_id', 'road_type', 'surface_type_clean', 'speed_kmh', 'lanes',
       'walkability_score', 'walkability_class', 'district', 'year',
       'geometry', 'infra_score', 'infra_score_scaled', 'final_score',
       'final_class'],
      dtype='str')

In [145]:
gdf_join = gpd.sjoin(
    gdf_final[["street_id", "geometry"]],
    gdf_proof_areas[["nutzung", "geometry"]],
    how="left",
    predicate="intersects"
)

print(gdf_join.shape)
gdf_join.head()

/var/folders/44/4bwz988s0nz2kzlgp5nnzdl80000gn/T/ipykernel_30429/4243236520.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:25832
Right CRS: EPSG:4326

  gdf_join = gpd.sjoin(

(519, 4)

,street_id,geometry,index_right,nutzung
0,0,"LINESTRING (569339.339 5936492.957, 569336.149...",NaN,NaN
1,1,"LINESTRING (569336.149 5936501.685, 569329.452...",NaN,NaN
2,2,"LINESTRING (569139.08 5936499.57, 569147.227 5...",NaN,NaN
3,3,"LINESTRING (569329.313 5936520.723, 569326.661...",NaN,NaN
4,4,"LINESTRING (569326.661 5936529.92, 569325.085 ...",NaN,NaN

# Preparation of sidewalk for walkability

In [146]:
import geopandas as gpd
import pandas as pd

gdf_areas = gpd.read_file("../data/prep/prep_street_areas.gpkg")

In [147]:
surface_stats = (
    gdf_areas
    .groupby("inhalt")
    .agg(
        n_polygons=("inhalt", "count"),
        total_area=("area_m2", "sum")
    )
    .sort_values("total_area", ascending=False)
)

surface_stats.head(30)

                                           n_polygons    total_area
inhalt
Asphalt                                         77110  2.679449e+07
Grasfläche, Wiese                              111994  6.828721e+06
Platten sonstige                               101992  5.424678e+06
Platten 50x50                                   84098  3.610254e+06
Betonstein sonstige                             82450  3.149327e+06
Natursteinpflaster                              41785  2.433053e+06
wassergebunden (Grandfläche)                    62797  1.918201e+06
Gehölz, Baumbestand                              6336  1.796354e+06
Betonsteinpflaster 10x20                        31888  1.207172e+06
Betonwabenstein                                 52194  1.202326e+06
Fremdnutzung                                    19044  1.080199e+06
unbefestigt (keine Grandfläche)                 23620  9.951910e+05
Betonsteinpflaster 25x25                        19975  9.791892e+05
Graben                                          12572  6.916167e+05
Sträucher ab 1m Höhe                            11456  5.570816e+05
Sukzession, Wildwuchs                            3848  5.311303e+05
durchgewachsene Grandfläche                     16441  5.231598e+05
Sträucher und Bodendecker bis 1m Höhe            9963  4.302788e+05
Baumscheibe bepflanzt, Rindenmulch              32682  3.434326e+05
(z.Zt) vegetationslos                           16734  3.046524e+05
Beton                                            5869  2.691761e+05
Rinne                                            8776  2.501227e+05
Hecke                                           10674  1.447521e+05
Böschung bewachsen                                699  1.107330e+05
Platten 50x75                                    2636  1.000984e+05
Gebäude                                           864  8.855149e+04
Baumscheibe unbegrünt                            9430  6.400423e+04
Baumscheibe wassergebunden durchgewachsen        7206  5.930430e+04
Rasengittersteine                                3054  5.829064e+04
Kunststein                                        149  4.202902e+04

In [148]:
import pandas as pd

surface_lookup = pd.DataFrame([

    {
        "inhalt": "Asphalt",
        "material_en": "Asphalt",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe befestigt (Grand)",
        "material_en": "Tree pit (gravel)",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe befestigt (Stahlgitter, Kunststoff)",
        "material_en": "Tree pit (steel grate / plastic)",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe begrünt",
        "material_en": "Vegetated tree pit",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe bepflanzt, Rindenmulch",
        "material_en": "Mulched tree pit",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe unbegrünt",
        "material_en": "Unplanted tree pit",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baumscheibe wassergebunden durchgewachsen",
        "material_en": "Vegetated gravel tree pit",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Baustelle",
        "material_en": "Construction site",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Bäche",
        "material_en": "Streams",
        "class": "water",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "bepflanzt (Sommerblumen, Rosen, Staudenbeet)",
        "material_en": "Flower bed",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Beton",
        "material_en": "Concrete",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Betonstein sonstige",
        "material_en": "Other concrete block paving",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Betonsteinpflaster 10x20",
        "material_en": "Concrete block paving 10×20",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Betonsteinpflaster 25x25",
        "material_en": "Concrete block paving 25×25",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Betonwabenstein",
        "material_en": "Concrete grid pavers",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Böschung befestigt",
        "material_en": "Reinforced embankment",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Böschung bewachsen",
        "material_en": "Vegetated embankment",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Brücken, Stege, Wasserbauwerke",
        "material_en": "Bridge / Boardwalk / Hydraulic structure",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "durchgewachsene Grandfläche",
        "material_en": "Vegetated gravel surface",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Fremdnutzung",
        "material_en": "Other land use",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Gebäude",
        "material_en": "Building",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Gehölz, Baumbestand",
        "material_en": "Trees / Woodland",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Graben",
        "material_en": "Ditch",
        "class": "water",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Grasfläche, Wiese",
        "material_en": "Grass / Lawn",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Hafenbecken, Schleusenbecken, Kanal",
        "material_en": "Harbour basin / Canal",
        "class": "water",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Hecke",
        "material_en": "Hedge",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Hochbeet",
        "material_en": "Raised planting bed",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Kies (kein Weg)",
        "material_en": "Gravel (non-walkway)",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Kunststein",
        "material_en": "Artificial stone",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },

    # <<< HIER GEHT ES IM TEIL 2 WEITER >>>

        {
        "inhalt": "Mauer",
        "material_en": "Wall",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Mischmaterial",
        "material_en": "Mixed surface",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Natursteinpflaster",
        "material_en": "Natural stone paving",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Platten 50x50",
        "material_en": "Concrete slabs 50×50",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Platten 50x75",
        "material_en": "Concrete slabs 50×75",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Platten sonstige",
        "material_en": "Other concrete slabs",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Rasenwaben",
        "material_en": "Grass grid pavers",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Rasengittersteine",
        "material_en": "Grass grid pavers",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Regenrückhaltebecken",
        "material_en": "Stormwater retention basin",
        "class": "water",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Rinne",
        "material_en": "Drainage channel",
        "class": "excluded",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Sträucher ab 1m Höhe",
        "material_en": "Shrubs (>1 m)",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Sträucher und Bodendecker bis 1m Höhe",
        "material_en": "Shrubs & ground cover (<1 m)",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Sukzession, Wildwuchs",
        "material_en": "Natural vegetation",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "Teiche, See, Brack",
        "material_en": "Pond / Lake",
        "class": "water",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "unbefestigt (keine Grandfläche)",
        "material_en": "Unpaved surface",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "wassergebunden (Grandfläche)",
        "material_en": "Gravel surface",
        "class": "surface",
        "walkable": True,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    },
    {
        "inhalt": "(z.Zt) vegetationslos",
        "material_en": "Bare soil",
        "class": "green",
        "walkable": False,
        "comfort": pd.NA,
        "accessibility": pd.NA,
        "ecology": pd.NA
    }

])

# Comfort
surface_lookup["comfort"] = pd.NA
surface_lookup["comfort_reason"] = pd.NA
surface_lookup["comfort_source"] = pd.NA

# Accessibility
surface_lookup["accessibility"] = pd.NA
surface_lookup["accessibility_reason"] = pd.NA
surface_lookup["accessibility_source"] = pd.NA

# Ecology
surface_lookup["ecology"] = pd.NA
surface_lookup["ecology_reason"] = pd.NA
surface_lookup["ecology_source"] = pd.NA

# Condition
surface_lookup["condition"] = pd.NA
surface_lookup["condition_reason"] = "Not available in source data."
surface_lookup["condition_source"] = (
    "Source dataset contains no pavement condition information."
)

In [149]:
surface_lookup.to_csv(
    "../data/lookup/surface_material_scores.csv",
    index=False
)

In [150]:
surface_lookup

,inhalt,material_en,class,walkable,comfort,accessibility,ecology,comfort_reason,comfort_source,accessibility_reason,accessibility_source,ecology_reason,ecology_source,condition,condition_reason,condition_source
0,Asphalt,Asphalt,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
1,Baumscheibe befestigt (Grand),Tree pit (gravel),green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
2,"Baumscheibe befestigt (Stahlgitter, Kunststoff)",Tree pit (steel grate / plastic),green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
3,Baumscheibe begrünt,Vegetated tree pit,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
4,"Baumscheibe bepflanzt, Rindenmulch",Mulched tree pit,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
5,Baumscheibe unbegrünt,Unplanted tree pit,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
6,Baumscheibe wassergebunden durchgewachsen,Vegetated gravel tree pit,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
7,Baustelle,Construction site,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
8,Bäche,Streams,water,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
9,"bepflanzt (Sommerblumen, Rosen, Staudenbeet)",Flower bed,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
10,Beton,Concrete,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
11,Betonstein sonstige,Other concrete block paving,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
12,Betonsteinpflaster 10x20,Concrete block paving 10×20,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
13,Betonsteinpflaster 25x25,Concrete block paving 25×25,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
14,Betonwabenstein,Concrete grid pavers,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
15,Böschung befestigt,Reinforced embankment,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
16,Böschung bewachsen,Vegetated embankment,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
17,"Brücken, Stege, Wasserbauwerke",Bridge / Boardwalk / Hydraulic structure,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
18,durchgewachsene Grandfläche,Vegetated gravel surface,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
19,Fremdnutzung,Other land use,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
20,Gebäude,Building,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
21,"Gehölz, Baumbestand",Trees / Woodland,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
22,Graben,Ditch,water,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
23,"Grasfläche, Wiese",Grass / Lawn,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
24,"Hafenbecken, Schleusenbecken, Kanal",Harbour basin / Canal,water,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
25,Hecke,Hedge,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
26,Hochbeet,Raised planting bed,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
27,Kies (kein Weg),Gravel (non-walkway),excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
28,Kunststein,Artificial stone,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
29,Mauer,Wall,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
30,Mischmaterial,Mixed surface,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
31,Natursteinpflaster,Natural stone paving,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
32,Platten 50x50,Concrete slabs 50×50,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
33,Platten 50x75,Concrete slabs 50×75,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
34,Platten sonstige,Other concrete slabs,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
35,Rasenwaben,Grass grid pavers,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
36,Rasengittersteine,Grass grid pavers,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
37,Regenrückhaltebecken,Stormwater retention basin,water,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
38,Rinne,Drainage channel,excluded,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
39,Sträucher ab 1m Höhe,Shrubs (>1 m),green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
40,Sträucher und Bodendecker bis 1m Höhe,Shrubs & ground cover (<1 m),green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
41,"Sukzession, Wildwuchs",Natural vegetation,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
42,"Teiche, See, Brack",Pond / Lake,water,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
43,unbefestigt (keine Grandfläche),Unpaved surface,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
44,wassergebunden (Grandfläche),Gravel surface,surface,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...
45,(z.Zt) vegetationslos,Bare soil,green,False,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not available in source data.,Source dataset contains no pavement condition ...

In [151]:
import geopandas as gpd
import pandas as pd

In [152]:
gdf_areas = gpd.read_file("../data/prep/prep_street_areas.gpkg")

surface_lookup = pd.read_csv(
    "../data/lookup/surface_material_scores.csv"
)

In [153]:
gdf_surface = gdf_areas.merge(
    surface_lookup,
    on="inhalt",
    how="left",
    validate="many_to_one"
)

In [154]:
gdf_surface[
    gdf_surface["material_en"].isna()
]["inhalt"].unique()

<StringArray>
[]
Length: 0, dtype: str

In [155]:
# Anzahl der Datensätze vor und nach dem Merge vergleichen
len(gdf_areas), len(gdf_surface)

(879456, 879456)

## Score für sidewalk comfort

In [156]:
# Prüfen, ob alle walkable-Werte gesetzt sind
gdf_surface["walkable"].value_counts(dropna=False)

walkable
True     606240
False    273216
Name: count, dtype: int64

In [157]:
comfort_scores = {
    # Sehr hoher Gehkomfort
    "Asphalt": 5,
    "Beton": 5,
    "Platten 50x50": 5,
    "Platten 50x75": 5,
    "Platten sonstige": 5,

    # Hoher Gehkomfort
    "Betonsteinpflaster 25x25": 4,
    "Betonsteinpflaster 10x20": 4,
    "Betonstein sonstige": 4,
    "Kunststein": 4,

    # Mittlerer Gehkomfort
    "Mischmaterial": 3,
    "wassergebunden (Grandfläche)": 3,
    "durchgewachsene Grandfläche": 3,
    "Rasenwaben": 3,
    "Rasengittersteine": 3,

    # Geringer Gehkomfort
    "Natursteinpflaster": 2,
    "unbefestigt (keine Grandfläche)": 2
}

In [158]:
surface_lookup["comfort"] = (
    surface_lookup["inhalt"]
    .map(comfort_scores)
)

In [159]:
comfort_reasons = {
    "Asphalt": "Smooth, even and low-vibration surface.",
    "Beton": "Smooth, even and stable surface.",
    "Platten 50x50": "Large slabs with smooth walking surface.",
    "Platten 50x75": "Large slabs with smooth walking surface.",
    "Platten sonstige": "Smooth slab surface with minor joints.",

    "Betonsteinpflaster 25x25": "Regular paving with moderate joints.",
    "Betonsteinpflaster 10x20": "Regular paving with moderate joints.",
    "Betonstein sonstige": "Concrete block paving with moderate walking comfort.",
    "Kunststein": "Generally smooth but with joints.",

    "Mischmaterial": "Mixed surface with varying walking comfort.",
    "wassergebunden (Grandfläche)": "Firm gravel surface with moderate vibration.",
    "durchgewachsene Grandfläche": "Vegetated gravel surface with moderate comfort.",
    "Rasenwaben": "Grass grid surface with uneven walking feel.",
    "Rasengittersteine": "Grass grid surface with uneven walking feel.",

    "Natursteinpflaster": "Uneven natural stone surface with noticeable vibration.",
    "unbefestigt (keine Grandfläche)": "Loose unpaved surface with reduced walking comfort."
}

surface_lookup["comfort_reason"] = (
    surface_lookup["inhalt"]
    .map(comfort_reasons)
)

In [160]:
surface_lookup.dtypes

inhalt                      str
material_en                 str
class                       str
walkable                   bool
comfort                 float64
accessibility           float64
ecology                 float64
comfort_reason              str
comfort_source          float64
accessibility_reason    float64
accessibility_source    float64
ecology_reason          float64
ecology_source          float64
condition               float64
condition_reason            str
condition_source            str
dtype: object

In [161]:
text_cols = [
    "comfort_reason",
    "comfort_source",
    "accessibility_reason",
    "accessibility_source",
    "ecology_reason",
    "ecology_source",
    "condition_reason",
    "condition_source"
]

surface_lookup[text_cols] = surface_lookup[text_cols].astype("string")

In [162]:
surface_lookup["comfort_source"] = (
    surface_lookup["comfort_source"]
    .astype("string")
)

In [163]:
surface_lookup.loc[
    surface_lookup["comfort"].notna(),
    "comfort_source"
] = "Own assessment based on surface characteristics."

In [164]:
surface_lookup.head

<bound method NDFrame.head of                                              inhalt  \
0                                           Asphalt
1                     Baumscheibe befestigt (Grand)
2   Baumscheibe befestigt (Stahlgitter, Kunststoff)
3                               Baumscheibe begrünt
4                Baumscheibe bepflanzt, Rindenmulch
5                             Baumscheibe unbegrünt
6         Baumscheibe wassergebunden durchgewachsen
7                                         Baustelle
8                                             Bäche
9      bepflanzt (Sommerblumen, Rosen, Staudenbeet)
10                                            Beton
11                              Betonstein sonstige
12                         Betonsteinpflaster 10x20
13                         Betonsteinpflaster 25x25
14                                  Betonwabenstein
15                               Böschung befestigt
16                               Böschung bewachsen
17                   Brücken, Stege, Wasserbauwerke
18                      durchgewachsene Grandfläche
19                                     Fremdnutzung
20                                          Gebäude
21                              Gehölz, Baumbestand
22                                           Graben
23                                Grasfläche, Wiese
24              Hafenbecken, Schleusenbecken, Kanal
25                                            Hecke
26                                         Hochbeet
27                                  Kies (kein Weg)
28                                       Kunststein
29                                            Mauer
30                                    Mischmaterial
31                               Natursteinpflaster
32                                    Platten 50x50
33                                    Platten 50x75
34                                 Platten sonstige
35                                       Rasenwaben
36                                Rasengittersteine
37                             Regenrückhaltebecken
38                                            Rinne
39                             Sträucher ab 1m Höhe
40            Sträucher und Bodendecker bis 1m Höhe
41                            Sukzession, Wildwuchs
42                               Teiche, See, Brack
43                  unbefestigt (keine Grandfläche)
44                     wassergebunden (Grandfläche)
45                            (z.Zt) vegetationslos

                                 material_en     class  walkable  comfort  \
0                                    Asphalt   surface      True      5.0
1                          Tree pit (gravel)     green     False      NaN
2           Tree pit (steel grate / plastic)     green     False      NaN
3                         Vegetated tree pit     green     False      NaN
4                           Mulched tree pit     green     False      NaN
5                         Unplanted tree pit     green     False      NaN
6                  Vegetated gravel tree pit     green     False      NaN
7                          Construction site  excluded     False      NaN
8                                    Streams     water     False      NaN
9                                 Flower bed     green     False      NaN
10                                  Concrete   surface      True      5.0
11               Other concrete block paving   surface      True      4.0
12               Concrete block paving 10×20   surface      True      4.0
13               Concrete block paving 25×25   surface      True      4.0
14                      Concrete grid pavers   surface      True      NaN
15                     Reinforced embankment  excluded     False      NaN
16                      Vegetated embankment     green     False      NaN
17  Bridge / Boardwalk / Hydraulic structure  excluded     False      NaN
18                  Vegetated gravel surface   surface      True      3.0
19                            Other land use  excluded     False      NaN
20                                  Building  excluded     False      NaN
21                          Trees / Woodland     green     False      NaN
22                                     Ditch     water     False      NaN
23                              Grass / Lawn     green     False      NaN
24                     Harbour basin / Canal     water     False      NaN
25                                     Hedge     green     False      NaN
26                       Raised planting bed     green     False      NaN
27                      Gravel (non-walkway)  excluded     False      NaN
28                          Artificial stone   surface      True      4.0
29                                      Wall  excluded     False      NaN
30                             Mixed surface   surface      True      3.0
31                      Natural stone paving   surface      True      2.0
32                      Concrete slabs 50×50   surface      True      5.0
33                      Concrete slabs 50×75   surface      True      5.0
34                      Other concrete slabs   surface      True      5.0
35                         Grass grid pavers   surface      True      3.0
36                         Grass grid pavers   surface      True      3.0
37                Stormwater retention basin     water     False      NaN
38                          Drainage channel  excluded     False      NaN
39                             Shrubs (>1 m)     green     False      NaN
40              Shrubs & ground cover (<1 m)     green     False      NaN
41                        Natural vegetation     green     False      NaN
42                               Pond / Lake     water     False      NaN
43                           Unpaved surface   surface      True      2.0
44                            Gravel surface   surface      True      3.0
45                                 Bare soil     green     False      NaN

    accessibility  ecology                                     comfort_reason  \
0             NaN      NaN            Smooth, even and low-vibration surface.
1             NaN      NaN                                               <NA>
2             NaN      NaN                                               <NA>
3             NaN      NaN                                               <NA>
4             NaN      NaN                                               <NA>
5             NaN      NaN                                               <NA>
6             NaN      NaN                                               <NA>
7             NaN      NaN                                               <NA>
8             NaN      NaN                                               <NA>
9             NaN      NaN                                               <NA>
10            NaN      NaN                   Smooth, even and stable surface.
11            NaN      NaN  Concrete block paving with moderate walking co...
12            NaN      NaN               Regular paving with moderate joints.
13            NaN      NaN               Regular paving with moderate joints.
14            NaN      NaN                                               <NA>
15            NaN      NaN                                               <NA>
16            NaN      NaN                                               <NA>
17            NaN      NaN                                               <NA>
18            NaN      NaN    Vegetated gravel surface with moderate comfort.
19            NaN      NaN                                               <NA>
20            NaN      NaN                                               <NA>
21            NaN      NaN                                               <NA>
22            NaN      NaN                                               <NA>
23            NaN      NaN                                               <NA>
24            NaN      NaN                                               <NA>
25            NaN      NaN                                               <NA>
26            NaN      NaN                                               <NA>
27            NaN      NaN                                               <NA>
28            NaN      NaN                  Generally smooth but with joints.
29            NaN      NaN                                               <NA>
30            NaN      NaN        Mixed surface with varying walking comfort.
31            NaN      NaN  Uneven natural stone surface with noticeable v...
32            NaN      NaN           Large slabs with smooth walking surface.
33            NaN      NaN           Large slabs with smooth walking surface.
34            NaN      NaN             Smooth slab surface with minor joints.
35            NaN      NaN       Grass grid surface with uneven walking feel.
36            NaN      NaN       Grass grid surface with uneven walking feel.
37            NaN      NaN                                               <NA>
38            NaN      NaN                                               <NA>
39            NaN      NaN                                               <NA>
40            NaN      NaN                                               <NA>
41            NaN      NaN                                               <NA>
42            NaN      NaN                                               <NA>
43            NaN      NaN  Loose unpaved surface with reduced walking com...
44            NaN      NaN       Firm gravel surface with moderate vibration.
45            NaN      NaN                                               <NA>

                                      comfort_source accessibility_reason  \
0   Own assessment based on surface characteristics.                 <NA>
1                                               <NA>                 <NA>
2                                               <NA>                 <NA>
3                                               <NA>                 <NA>
4                                               <NA>                 <NA>
5                                               <NA>                 <NA>
6                                               <NA>                 <NA>
7                                               <NA>                 <NA>
8                                               <NA>                 <NA>
9                                               <NA>                 <NA>
10  Own assessment based on surface characteristics.                 <NA>
11  Own assessment based on surface characteristics.                 <NA>
12  Own assessment based on surface characteristics.                 <NA>
13  Own assessment based on surface characteristics.                 <NA>
14                                              <NA>                 <NA>
15                                              <NA>                 <NA>
16                                              <NA>                 <NA>
17                                              <NA>                 <NA>
18  Own assessment based on surface characteristics.                 <NA>
19                                              <NA>                 <NA>
20                                              <NA>                 <NA>
21                                              <NA>                 <NA>
22                                              <NA>                 <NA>
23                                              <NA>                 <NA>
24                                              <NA>                 <NA>
25                                              <NA>                 <NA>
26                                              <NA>                 <NA>
27                                              <NA>                 <NA>
28  Own assessment based on surface characteristics.                 <NA>
29                                              <NA>                 <NA>
30  Own assessment based on surface characteristics.                 <NA>
31  Own assessment based on surface characteristics.                 <NA>
32  Own assessment based on surface characteristics.                 <NA>
33  Own assessment based on surface characteristics.                 <NA>
34  Own assessment based on surface characteristics.                 <NA>
35  Own assessment based on surface characteristics.                 <NA>
36  Own assessment based on surface characteristics.                 <NA>
37                                              <NA>                 <NA>
38                                              <NA>                 <NA>
39                                              <NA>                 <NA>
40                                              <NA>                 <NA>
41                                              <NA>                 <NA>
42                                              <NA>                 <NA>
43  Own assessment based on surface characteristics.                 <NA>
44  Own assessment based on surface characteristics.                 <NA>
45                                              <NA>                 <NA>

   accessibility_source ecology_reason ecology_source  condition  \
0                  <NA>           <NA>           <NA>        NaN
1                  <NA>           <NA>           <NA>        NaN
2                  <NA>           <NA>           <NA>        NaN
3                  <NA>           <NA>           <NA>        NaN
4                  <NA>           <NA>           <NA>        NaN
5                  <NA>           <NA>           <NA>        NaN
6                  <NA>           <NA>           <NA>        NaN
7                  <NA>           <NA>           <NA>        NaN
8                  <NA>           <NA>           <NA>        NaN
9                  <NA>           <NA>           <NA>        NaN
10                 <NA>           <NA>           <NA>        NaN
11                 <NA>           <NA>           <NA>        NaN
12                 <NA>           <NA>           <NA>        NaN
13                 <NA>           <NA>           <NA>        NaN
14                 <NA>           <NA>           <NA>        NaN
15                 <NA>           <NA>           <NA>        NaN
16                 <NA>           <NA>           <NA>        NaN
17                 <NA>           <NA>           <NA>        NaN
18                 <NA>           <NA>           <NA>        NaN
19                 <NA>           <NA>           <NA>        NaN
20                 <NA>           <NA>           <NA>        NaN
21                 <NA>           <NA>           <NA>        NaN
22                 <NA>           <NA>           <NA>        NaN
23                 <NA>           <NA>           <NA>        NaN
24                 <NA>           <NA>           <NA>        NaN
25                 <NA>           <NA>           <NA>        NaN
26                 <NA>           <NA>           <NA>        NaN
27                 <NA>           <NA>           <NA>        NaN
28                 <NA>           <NA>           <NA>        NaN
29                 <NA>           <NA>           <NA>        NaN
30                 <NA>           <NA>           <NA>        NaN
31                 <NA>           <NA>           <NA>        NaN
32                 <NA>           <NA>           <NA>        NaN
33                 <NA>           <NA>           <NA>        NaN
34                 <NA>           <NA>           <NA>        NaN
35                 <NA>           <NA>           <NA>        NaN
36                 <NA>           <NA>           <NA>        NaN
37                 <NA>           <NA>           <NA>        NaN
38                 <NA>           <NA>           <NA>        NaN
39                 <NA>           <NA>           <NA>        NaN
40                 <NA>           <NA>           <NA>        NaN
41                 <NA>           <NA>           <NA>        NaN
42                 <NA>           <NA>           <NA>        NaN
43                 <NA>           <NA>           <NA>        NaN
44                 <NA>           <NA>           <NA>        NaN
45                 <NA>           <NA>           <NA>        NaN

                 condition_reason  \
0   Not available in source data.
1   Not available in source data.
2   Not available in source data.
3   Not available in source data.
4   Not available in source data.
5   Not available in source data.
6   Not available in source data.
7   Not available in source data.
8   Not available in source data.
9   Not available in source data.
10  Not available in source data.
11  Not available in source data.
12  Not available in source data.
13  Not available in source data.
14  Not available in source data.
15  Not available in source data.
16  Not available in source data.
17  Not available in source data.
18  Not available in source data.
19  Not available in source data.
20  Not available in source data.
21  Not available in source data.
22  Not available in source data.
23  Not available in source data.
24  Not available in source data.
25  Not available in source data.
26  Not available in source data.
27  Not available in source data.
28  Not available in source data.
29  Not available in source data.
30  Not available in source data.
31  Not available in source data.
32  Not available in source data.
33  Not available in source data.
34  Not available in source data.
35  Not available in source data.
36  Not available in source data.
37  Not available in source data.
38  Not available in source data.
39  Not available in source data.
40  Not available in source data.
41  Not available in source data.
42  Not available in source data.
43  Not available in source data.
44  Not available in source data.
45  Not available in source data.

                                     condition_source
0   Source dataset contains no pavement condition ...
1   Source dataset contains no pavement condition ...
2   Source dataset contains no pavement condition ...
3   Source dataset contains no pavement condition ...
4   Source dataset contains no pavement condition ...
5   Source dataset contains no pavement condition ...
6   Source dataset contains no pavement condition ...
7   Source dataset contains no pavement condition ...
8   Source dataset contains no pavement condition ...
9   Source dataset contains no pavement condition ...
10  Source dataset contains no pavement condition ...
11  Source dataset contains no pavement condition ...
12  Source dataset contains no pavement condition ...
13  Source dataset contains no pavement condition ...
14  Source dataset contains no pavement condition ...
15  Source dataset contains no pavement condition ...
16  Source dataset contains no pavement condition ...
17  Source dataset contains no pavement condition ...
18  Source dataset contains no pavement condition ...
19  Source dataset contains no pavement condition ...
20  Source dataset contains no pavement condition ...
21  Source dataset contains no pavement condition ...
22  Source dataset contains no pavement condition ...
23  Source dataset contains no pavement condition ...
24  Source dataset contains no pavement condition ...
25  Source dataset contains no pavement condition ...
26  Source dataset contains no pavement condition ...
27  Source dataset contains no pavement condition ...
28  Source dataset contains no pavement condition ...
29  Source dataset contains no pavement condition ...
30  Source dataset contains no pavement condition ...
31  Source dataset contains no pavement condition ...
32  Source dataset contains no pavement condition ...
33  Source dataset contains no pavement condition ...
34  Source dataset contains no pavement condition ...
35  Source dataset contains no pavement condition ...
36  Source dataset contains no pavement condition ...
37  Source dataset contains no pavement condition ...
38  Source dataset contains no pavement condition ...
39  Source dataset contains no pavement condition ...

In [165]:
text_cols = [
    "comfort_reason",
    "comfort_source",
    "accessibility_reason",
    "accessibility_source",
    "ecology_reason",
    "ecology_source",
    "condition_reason",
    "condition_source"
]

for col in text_cols:
    surface_lookup[col] = pd.Series(pd.NA, index=surface_lookup.index, dtype="string")

In [181]:
comfort_scores = {
    # Very high walking comfort
    "Asphalt": 5,
    "Beton": 5,
    "Platten 50x50": 5,
    "Platten 50x75": 5,
    "Platten sonstige": 5,

    # High walking comfort
    "Betonsteinpflaster 10x20": 4,
    "Betonsteinpflaster 25x25": 4,
    "Betonstein sonstige": 4,
    "Kunststein": 4,

    # Moderate walking comfort
    "wassergebunden (Grandfläche)": 3,
    "durchgewachsene Grandfläche": 3,
    "Mischmaterial": 3,
    "Betonwabenstein": 3,
    "Rasenwaben": 3,
    "Rasengittersteine": 3,

    # Low walking comfort
    "Natursteinpflaster": 2,
    "unbefestigt (keine Grandfläche)": 2
}

In [182]:
comfort_reasons = {
    "Asphalt": "Smooth, even and continuous surface providing very high walking comfort.",
    "Beton": "Firm, even and stable surface with very high walking comfort.",
    "Platten 50x50": "Large slabs with few joints, resulting in a smooth walking surface.",
    "Platten 50x75": "Large slabs with few joints, providing excellent walking comfort.",
    "Platten sonstige": "Slab surfaces generally provide high walking comfort due to their evenness.",

    "Betonsteinpflaster 10x20": "Regular concrete paving with moderate joints causing minor vibration.",
    "Betonsteinpflaster 25x25": "Regular paving pattern with good walking comfort despite visible joints.",
    "Betonstein sonstige": "Concrete block paving provides good walking comfort with moderate surface vibration.",
    "Kunststein": "Artificial stone surfaces are generally smooth but include joints that slightly reduce comfort.",

    "wassergebunden (Grandfläche)": "Firm gravel surface providing moderate walking comfort.",
    "durchgewachsene Grandfläche": "Vegetation within the gravel surface slightly reduces walking comfort.",
    "Mischmaterial": "Walking comfort depends on the material mix and is therefore moderate.",
    "Rasenwaben": "Grass grid surface is walkable but produces an uneven walking sensation.",
    "Betonwabenstein": "Concrete cellular paving provides a firm but uneven walking surface with moderate walking comfort.",
    "Rasengittersteine": "Grass grid pavers create an uneven but still walkable surface.",

    "Natursteinpflaster": "Irregular natural stone surface results in noticeable vibration while walking.",
    "unbefestigt (keine Grandfläche)": "Loose unpaved surface provides limited walking comfort."
}

In [183]:
surface_lookup["comfort"] = surface_lookup["inhalt"].map(comfort_scores)

surface_lookup["comfort_reason"] = surface_lookup["inhalt"].map(comfort_reasons)

In [184]:
AUTHOR = "Author's assessment based on material characteristics."

In [185]:
surface_lookup.loc[
    surface_lookup["comfort"].notna(),
    "comfort_source"
] = AUTHOR

In [186]:
surface_lookup.loc[
    (surface_lookup["walkable"] == True) &
    (surface_lookup["comfort"].isna()),
    ["inhalt", "walkable", "comfort"]
]

Empty DataFrame
Columns: [inhalt, walkable, comfort]
Index: []

In [187]:
surface_lookup.loc[
    surface_lookup["comfort"].notna() &
    surface_lookup["comfort_reason"].isna(),
    ["inhalt", "comfort"]
]

Empty DataFrame
Columns: [inhalt, comfort]
Index: []

In [188]:
surface_lookup.loc[
    surface_lookup["comfort"].notna() &
    surface_lookup["comfort_source"].isna(),
    ["inhalt", "comfort"]
]

Empty DataFrame
Columns: [inhalt, comfort]
Index: []

In [189]:
surface_lookup[
    ["comfort",
     "comfort_reason",
     "comfort_source"]
].dtypes

comfort           float64
comfort_reason        str
comfort_source     string
dtype: object

In [190]:
surface_lookup[
    ["inhalt", "comfort", "comfort_reason"]
].sort_values("comfort", ascending=False)

,inhalt,comfort,comfort_reason
0,Asphalt,5.0,"Smooth, even and continuous surface providing ..."
33,Platten 50x75,5.0,"Large slabs with few joints, providing excelle..."
10,Beton,5.0,"Firm, even and stable surface with very high w..."
34,Platten sonstige,5.0,Slab surfaces generally provide high walking c...
32,Platten 50x50,5.0,"Large slabs with few joints, resulting in a sm..."
11,Betonstein sonstige,4.0,Concrete block paving provides good walking co...
12,Betonsteinpflaster 10x20,4.0,Regular concrete paving with moderate joints c...
13,Betonsteinpflaster 25x25,4.0,Regular paving pattern with good walking comfo...
28,Kunststein,4.0,Artificial stone surfaces are generally smooth...
36,Rasengittersteine,3.0,Grass grid pavers create an uneven but still w...
35,Rasenwaben,3.0,Grass grid surface is walkable but produces an...
30,Mischmaterial,3.0,Walking comfort depends on the material mix an...
18,durchgewachsene Grandfläche,3.0,Vegetation within the gravel surface slightly ...
14,Betonwabenstein,3.0,Concrete cellular paving provides a firm but u...
44,wassergebunden (Grandfläche),3.0,Firm gravel surface providing moderate walking...
31,Natursteinpflaster,2.0,Irregular natural stone surface results in not...
43,unbefestigt (keine Grandfläche),2.0,Loose unpaved surface provides limited walking...
1,Baumscheibe befestigt (Grand),NaN,NaN
2,"Baumscheibe befestigt (Stahlgitter, Kunststoff)",NaN,NaN
3,Baumscheibe begrünt,NaN,NaN
4,"Baumscheibe bepflanzt, Rindenmulch",NaN,NaN
5,Baumscheibe unbegrünt,NaN,NaN
6,Baumscheibe wassergebunden durchgewachsen,NaN,NaN
7,Baustelle,NaN,NaN
8,Bäche,NaN,NaN
9,"bepflanzt (Sommerblumen, Rosen, Staudenbeet)",NaN,NaN
15,Böschung befestigt,NaN,NaN
16,Böschung bewachsen,NaN,NaN
17,"Brücken, Stege, Wasserbauwerke",NaN,NaN
19,Fremdnutzung,NaN,NaN
20,Gebäude,NaN,NaN
21,"Gehölz, Baumbestand",NaN,NaN
22,Graben,NaN,NaN
23,"Grasfläche, Wiese",NaN,NaN
24,"Hafenbecken, Schleusenbecken, Kanal",NaN,NaN
25,Hecke,NaN,NaN
26,Hochbeet,NaN,NaN
27,Kies (kein Weg),NaN,NaN
29,Mauer,NaN,NaN
37,Regenrückhaltebecken,NaN,NaN
38,Rinne,NaN,NaN
39,Sträucher ab 1m Höhe,NaN,NaN
40,Sträucher und Bodendecker bis 1m Höhe,NaN,NaN
41,"Sukzession, Wildwuchs",NaN,NaN
42,"Teiche, See, Brack",NaN,NaN
45,(z.Zt) vegetationslos,NaN,NaN

In [191]:
surface_lookup.loc[
    surface_lookup["comfort"].isna(),
    ["inhalt", "walkable"]
]

                                             inhalt  walkable
1                     Baumscheibe befestigt (Grand)     False
2   Baumscheibe befestigt (Stahlgitter, Kunststoff)     False
3                               Baumscheibe begrünt     False
4                Baumscheibe bepflanzt, Rindenmulch     False
5                             Baumscheibe unbegrünt     False
6         Baumscheibe wassergebunden durchgewachsen     False
7                                         Baustelle     False
8                                             Bäche     False
9      bepflanzt (Sommerblumen, Rosen, Staudenbeet)     False
15                               Böschung befestigt     False
16                               Böschung bewachsen     False
17                   Brücken, Stege, Wasserbauwerke     False
19                                     Fremdnutzung     False
20                                          Gebäude     False
21                              Gehölz, Baumbestand     False
22                                           Graben     False
23                                Grasfläche, Wiese     False
24              Hafenbecken, Schleusenbecken, Kanal     False
25                                            Hecke     False
26                                         Hochbeet     False
27                                  Kies (kein Weg)     False
29                                            Mauer     False
37                             Regenrückhaltebecken     False
38                                            Rinne     False
39                             Sträucher ab 1m Höhe     False
40            Sträucher und Bodendecker bis 1m Höhe     False
41                            Sukzession, Wildwuchs     False
42                               Teiche, See, Brack     False
45                            (z.Zt) vegetationslos     False

## Score für accessibility

In [192]:
accessibility_scores = {
    # Very high accessibility
    "Asphalt": 5,
    "Beton": 5,
    "Platten 50x50": 5,
    "Platten 50x75": 5,
    "Platten sonstige": 5,

    # High accessibility
    "Betonsteinpflaster 10x20": 4,
    "Betonsteinpflaster 25x25": 4,
    "Betonstein sonstige": 4,
    "Kunststein": 4,

    # Moderate accessibility
    "Mischmaterial": 3,

    # Limited accessibility
    "wassergebunden (Grandfläche)": 2,
    "durchgewachsene Grandfläche": 2,
    "Betonwabenstein": 2,

    # Poor accessibility
    "Natursteinpflaster": 1,
    "Rasenwaben": 1,
    "Rasengittersteine": 1,
    "unbefestigt (keine Grandfläche)": 1
}

In [193]:
accessibility_reasons = {
    "Asphalt": "Smooth, even and firm surface providing excellent accessibility for all users.",
    "Beton": "Firm and even surface offering excellent accessibility.",
    "Platten 50x50": "Large slabs with few joints provide very good accessibility.",
    "Platten 50x75": "Large slab paving with minimal joints supports easy movement.",
    "Platten sonstige": "Slab surfaces generally provide excellent accessibility due to their evenness.",

    "Betonsteinpflaster 10x20": "Regular concrete paving is generally accessible but joints may cause minor vibration.",
    "Betonsteinpflaster 25x25": "Concrete paving offers good accessibility despite surface joints.",
    "Betonstein sonstige": "Concrete block paving is generally accessible but less smooth than slab surfaces.",
    "Kunststein": "Artificial stone surfaces are generally even with moderate impact from joints.",

    "Mischmaterial": "Accessibility varies depending on the material composition.",

    "wassergebunden (Grandfläche)": "Firm gravel surfaces increase rolling resistance and may become difficult under wet conditions.",
    "durchgewachsene Grandfläche": "Vegetation and loose surface reduce accessibility for mobility aids.",
    "Betonwabenstein": "Concrete cellular paving creates an uneven surface that is difficult for small wheels and walking aids.",

    "Natursteinpflaster": "Irregular natural stone paving creates substantial barriers for wheelchairs and walking aids.",
    "Rasenwaben": "Grass grid surfaces are difficult to traverse with wheelchairs, walkers and strollers.",
    "Rasengittersteine": "Grass grid pavers contain large openings that significantly reduce accessibility.",
    "unbefestigt (keine Grandfläche)": "Loose unpaved surfaces are generally unsuitable for wheelchairs and walking aids."
}

In [194]:
AUTHOR = "Author's assessment based on material characteristics."

surface_lookup["accessibility"] = (
    surface_lookup["inhalt"]
    .map(accessibility_scores)
)

surface_lookup["accessibility_reason"] = (
    surface_lookup["inhalt"]
    .map(accessibility_reasons)
)

surface_lookup.loc[
    surface_lookup["accessibility"].notna(),
    "accessibility_source"
] = AUTHOR

In [195]:
surface_lookup.loc[
    (surface_lookup["walkable"]) &
    (surface_lookup["accessibility"].isna()),
    ["inhalt", "walkable", "accessibility"]
]

Empty DataFrame
Columns: [inhalt, walkable, accessibility]
Index: []

In [196]:
surface_lookup.loc[
    surface_lookup["accessibility"].notna() &
    surface_lookup["accessibility_reason"].isna(),
    ["inhalt", "accessibility"]
]

Empty DataFrame
Columns: [inhalt, accessibility]
Index: []

In [197]:
surface_lookup.loc[
    surface_lookup["accessibility"].notna() &
    surface_lookup["accessibility_source"].isna(),
    ["inhalt", "accessibility"]
]

Empty DataFrame
Columns: [inhalt, accessibility]
Index: []

In [198]:
surface_lookup.loc[
    (~surface_lookup["walkable"]) &
    (surface_lookup["accessibility"].notna()),
    ["inhalt", "walkable", "accessibility"]
]

Empty DataFrame
Columns: [inhalt, walkable, accessibility]
Index: []

In [199]:
surface_lookup[
    [
        "accessibility",
        "accessibility_reason",
        "accessibility_source"
    ]
].dtypes

accessibility           float64
accessibility_reason        str
accessibility_source     string
dtype: object

## Score für ecology

In [200]:
ecology_scores = {
    # Very low ecological value (sealed surfaces)
    "Asphalt": 1,
    "Beton": 1,

    # Low ecological value
    "Platten 50x50": 2,
    "Platten 50x75": 2,
    "Platten sonstige": 2,

    # Moderate ecological value
    "Betonsteinpflaster 10x20": 3,
    "Betonsteinpflaster 25x25": 3,
    "Betonstein sonstige": 3,
    "Kunststein": 3,
    "Natursteinpflaster": 3,
    "Betonwabenstein": 3,

    # High ecological value
    "Mischmaterial": 4,

    # Very high ecological value
    "wassergebunden (Grandfläche)": 5,
    "durchgewachsene Grandfläche": 5,
    "Rasenwaben": 5,
    "Rasengittersteine": 5,
    "unbefestigt (keine Grandfläche)": 5
}

In [201]:
ecology_reasons = {
    # Very low ecological value
    "Asphalt": "Impermeable sealed surface preventing water infiltration and limiting natural soil functions.",
    "Beton": "Impermeable sealed surface with very low ecological value due to restricted infiltration.",

    # Low ecological value
    "Platten 50x50": "Mostly sealed surface with limited water infiltration through joints.",
    "Platten 50x75": "Mostly sealed surface with limited permeability provided by joints.",
    "Platten sonstige": "Slab surfaces are predominantly sealed with only minor infiltration through joints.",

    # Moderate ecological value
    "Betonsteinpflaster 10x20": "Jointed paving allows partial water infiltration compared to sealed surfaces.",
    "Betonsteinpflaster 25x25": "Jointed paving provides moderate permeability and partial soil-water exchange.",
    "Betonstein sonstige": "Concrete block paving permits limited infiltration through joints.",
    "Kunststein": "Artificial stone paving provides moderate ecological value depending on joint permeability.",
    "Natursteinpflaster": "Natural stone paving typically allows partial infiltration through wider joints.",
    "Betonwabenstein": "Concrete cellular paving supports partial infiltration through open cells.",

    # High ecological value
    "Mischmaterial": "Mixed surface materials provide partial permeability and moderate ecological functions.",

    # Very high ecological value
    "wassergebunden (Grandfläche)": "Permeable surface supporting natural water infiltration and soil functions.",
    "durchgewachsene Grandfläche": "Permeable vegetated surface supporting infiltration and vegetation growth.",
    "Rasenwaben": "Vegetated permeable surface promoting infiltration and reducing surface sealing.",
    "Rasengittersteine": "Permeable grass grid surface supporting infiltration and vegetation.",
    "unbefestigt (keine Grandfläche)": "Natural unsealed surface providing maximum infiltration and ecological function."
}

In [202]:
surface_lookup["ecology"] = (
    surface_lookup["inhalt"]
    .map(ecology_scores)
)

surface_lookup["ecology_reason"] = (
    surface_lookup["inhalt"]
    .map(ecology_reasons)
)

surface_lookup.loc[
    surface_lookup["ecology"].notna(),
    "ecology_source"
] = AUTHOR

In [203]:
surface_lookup.loc[
    (surface_lookup["walkable"]) &
    (surface_lookup["ecology"].isna()),
    ["inhalt", "walkable", "ecology"]
]

Empty DataFrame
Columns: [inhalt, walkable, ecology]
Index: []

In [204]:
surface_lookup.loc[
    surface_lookup["ecology"].notna() &
    surface_lookup["ecology_reason"].isna(),
    ["inhalt", "ecology"]
]

Empty DataFrame
Columns: [inhalt, ecology]
Index: []

In [205]:
surface_lookup.loc[
    surface_lookup["ecology"].notna() &
    surface_lookup["ecology_source"].isna(),
    ["inhalt", "ecology"]
]

Empty DataFrame
Columns: [inhalt, ecology]
Index: []

In [206]:
surface_lookup.loc[
    (~surface_lookup["walkable"]) &
    (surface_lookup["ecology"].notna()),
    ["inhalt", "walkable", "ecology"]
]

Empty DataFrame
Columns: [inhalt, walkable, ecology]
Index: []

In [207]:
surface_lookup[
    [
        "ecology",
        "ecology_reason",
        "ecology_source"
    ]
].dtypes

ecology           float64
ecology_reason        str
ecology_source     string
dtype: object

# Barrierefreiheit: 

Bestehende Richtlinien anlehnen (noch vorbereiten!!!), bestehende Standards, zum Beispiel:

- Empfehlungen der FGSV (Forschungsgesellschaft für Straßen- und Verkehrswesen) zur Fußverkehrsinfrastruktur,

- DIN 18040 (Barrierefreies Bauen),
- kommunale Leitfäden zur Barrierefreiheit,
- internationale Forschung zu Walkability und Accessibility.
Begründung:
"Die Oberflächen wurden anhand der Kriterien Ebenheit, Rollbarkeit und Rutschfestigkeit bewertet. Die Gewichtung orientiert sich an den Anforderungen der Barrierefreiheit."

| Kriterium               | Warum relevant?                            |
| ----------------------- | ------------------------------------------ |
| Ebenheit                | Stolperrisiko, Gehkomfort                  |
| Rollbarkeit             | Rollstuhl, Rollator, Kinderwagen           |
| Rutschfestigkeit        | Sicherheit bei Nässe                       |
| Fugenbreite             | Einfluss auf Rollkomfort und Stolpergefahr |
| Versickerung/Grünanteil | Mikroklima, Aufenthaltsqualität            |

| `inhalt`        | Ebenheit | Rollbarkeit | Barrierefreiheit | Ökologie |
| --------------- | -------- | ----------- | ---------------- | -------- |
| Asphalt         | ?        | ?           | ?                | ?        |
| Platten 50x50   | ?        | ?           | ?                | ?        |
| Betonwabenstein | ?        | ?           | ?                | ?        |
| Kleinpflaster   | ?        | ?           | ?                | ?        |
| Grand           | ?        | ?           | ?                | ?        |